### ISSUE TITLE
Implementeer het informatiemodel als databasemodel

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#1]
**Tasks**

- [x] Create models for each entity (see attached, and page 35 of document 8)
- [x] Please use the Dutch terms for all model and field names!
- [x] Make sure the fields are up-to-date from the Excel file (document 11).

![image](https://user-images.githubusercontent.com/96970/127533147-03183bf5-3289-44f7-b869-e1d464841040.png)
