### ISSUE TITLE
[US-10] Als Gemeente Redactie wil ik een overzichtelijke lijst van producten, opdat ik in één oogopslag kan zien of ik voldoe aan de SDG 

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#11]
Om zicht te houden op de inrichting is het voor gebruikers wenselijk duidelijk te houden van welke producten reeds omschrijvingen t.b.v. de SDG zijn ingevoerd

**Acceptatiecriteria** :
- De gemeentelijke productlijst volgt de referentieteksten lijst (met unieke combi van UPN en doelgroep)
- producten zijn ingedeeld in de SDG informatiegebieden
- producten zijn gesorteerd op informatiegebied en daarbinnen op titel
- achter ieder product staat een icoon dat aangeeft welke teksten nog geschreven moeten worden, welke klaar zijn en welke nagekeken moeten worden.
	1. 	rood kruis (tekst niet gepubliceerd, u voldoet niet aan de SDG verordening)
	2. 	felle kleur uitroepteken (de referentietekst is gewijzigd, controleer uw specifieke tekst)
	3. 	groen minnetje (mijn gemeente voert dit product niet)
	4. 	groene vink (tekst geschreven)
- Per informatiegebied wordt het icoon met de hoogste prioriteit getoond (zie nummering hierboven). Oftewel achter een informatiegebied wordt alleen een groene vink getoon als alle producten binnen dit informatiegebied een groene vink hebben. Heeft één product een minnetje, toon dan het minnetje

**Tasks**

* [x] Add view/template to show all "informatiegebieden" (with products) and products (that are "beschikbaar") under that "informatiegebied" for the logged in municipality.
* [x] Per "informatiegebied" show how many "beschikbaar" products are in there (for the logged in municipality)
* [x] For each product, show the languages that are available

![image](https://user-images.githubusercontent.com/96970/130621922-899f70b4-2df1-41a3-bbb1-b9138904b9ac.png)
