### ISSUE TITLE
Als gemeentelijk redacteur beschik ik over een duidelijke inlogprocedure

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#118]
- [x] - Inlog button renamen naar 'inloggen'
- [x] - Auto aanmelden verwijderen
- [x] - vanuit de beheer interface worden nieuwe redacteuren aangemaakt
- [x] - nieuw aangemelde redacteuren ontvangen een bevestigingsmail

**Tasks**

* [x] In the admin, we can create a user, by passing its email-address, first- and last name, and assign role(s). This "in-between" screen is slightly different from Django default.

We can either adjust this screen or use a proxy model to register in the admin (EditorUser). Regular User modeladmin sees all. EditorUser sees only non-`is_staff` users and has a more simple edit screen without groups, and permissions (just the roles).

* [x] Automatically sent the created user an invite email so he/she can set his/her password and can have access.
