### ISSUE TITLE
[US-12] Als Gemeente Redactie wil ik een Product meertalig kunnen opstellen zodat ik kan voldoen aan de SDG-verordening

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#13]
De kern van de SDG

**Acceptatiecriteria** :
* voor elke taal (op dit moment NL en EN) is het mogelijk referentie en specifieke teksten op te stellen.

**Tasks**

Tip: Do #14 first.

* [x] Add "Wijzigen" button to go to the edit page of the product in that language.
* [x] Add edit page view/template/form for the product
* [x] Upon initial creation of the product (based on the reference product), fill the fields with the texts from the reference product.

![image](https://user-images.githubusercontent.com/96970/130623857-4d8d35ae-2cd9-4c86-b59c-a2ca5f49fb8d.png)

**Verduidelijking**

We will not add "follow the reference texts at all times"! The tasks below are removed:

* [x] ~Indicate (checkbox `..._use_reference`) below the text, whether this is a specific text, or a reference text (not in screenshot).~
* [x] ~Only if this checkbox is unchecked, you can edit the text.~

~In the end, there are 2 functions below each text field:~
~✅ Gebruik altijd de laatste referentie teksten  ♻️ Kopieer laatste referentie tekst in het tekstveld~
