### ISSUE TITLE
[US-13] Als Gemeente Redactie wil ik de referentieteksten kunnen gebruiken als specifieke tekst, opdat burgers en ondernemers voor één product bij meerdere gemeenten dezelfde teksten zien en opdat ik ontzorgd wordt #14 

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#14]
Referentieteksten worden:
* Binnen de invoervoorziening gebruikt ter ondersteuning van de gemeente redactie
* Buiten de invoervoorziening gebruikt om de burger te informeren

**Acceptatiecriteria** :
* Na het aanwijzen van een product zijn de relevante gegeven overzichtelijk aanwezig
* bovenin wordt altijd de generieke tekst getoond
* daaronder wordt de specifieke tekst getoond
  * als er nog geen specifieke tekst is, dan wordt deze aangemaakt en gevuld met een _**kopie van de referentietekst**_
  * per attribuut van de specifieke tekst kan de redacteur
    * de tekst wijzigen
    * de tekst 'resetten' naar de referentietekst
    * zien of de specifieke tekst gelijk is aan de referentietekst

De powerpoint [CimPDC en SDG.pptx](https://github.com/maykinmedia/sdg-invoervoorziening/files/7176408/CimPDC.en.SDG.pptx) bevat een uitwerking hoe in het informatiemodel vanuit een specifieke tekst wordt verwezen naar een referentietekst.

**Alternatieve oplossingen voor werken met referentietekst**
Voor nu is in de acceptatiecriteria gekozen voor het maken van een kopie van de referentietekst. Andere oplossingen die overwogen zijn:
* De specifieke tekst verwijst naar de meest actuele versie van de referentietekst
  * **+** gemeente redactie wordt maximaal ontzorgd. Als referentieteksten wijzigen (correctie, wetswijziging, ..) dan volgen de specifieke teksten zonder inspanning van de gemeente
  *  **-** specifieke teksten worden gewijzigd door de gezamenlijke redactie, terwijl de gemeente hiervoor verantwoordelijk is
* De specifieke tekst verwijst naar de versie van de referentietekst die door de gemeente is gezien en bevestigd
  * **+** gemeente redactie wordt ontzorgd, referentieteksten kunnen met minimale inspanning worden gebruikt
  * **+** gemeente heeft altijd expliciet voor een tekst gekozen
  * **+** voor gezamenlijke redactie maximaal inzicht in gebruik van referentieteksten
  * **-** na een wijziging van de referentietekst moet een gemeente deze actief kiezen, tot die tijd wordt de oude referentietekst getoond

**Tasks**

* [x] Add generic text above the specific text fields, as read only.
* [x] Add detail page view/template for a product (field name, field help text and field value)
* [x] If no specific text is available, show the reference text.
* [x] Show all available languages as tab. Each tab includes the product in the selected language.
* ~[ ] Adjust the models to include PER FIELD whether to use the specific information, or reference information as a boolean (`FIELD_use_reference` ie. `bewijs_use_reference` - default `True`).~
* [x] Add `get_FIELD` helpers to retrieve the specific text if present, otherwise the reference text.
* [x] For each field use the helpers to show the right text.
* [x] Show whether this is the reference or specific text (not in screenshot).

![image](https://user-images.githubusercontent.com/96970/130623336-54e27796-8f31-4fda-80a5-b17f11d74c09.png)
