### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#148]
**Tasks**

- [x] "Mandaag" -> "Maandag"
- [x] Rename "Roles" to "Gebruikers".
- [x] Remove "Gewijzigd" colomn on product details
- [x] Remove "Specifieke product" field on product details/edit page (this is some FK that shouldnt be there).
- [x] Rename "Gegeven" as column title on product details/edit page to "Specifieke gegevens"
- [x] "bezoek adres" -> "bezoekadres"
- [x] `publicatie_datum` (and datepicker) should just be a date (not time).
- [x] Cannot create/edit a referentie product in the admin -> (sentry) error
- [x] The admin does not properly show an add/remove button for arrayfields
- [x] Arrayfields are not properly shown in the CMS (should not show `[]` but simply nothing, and otherwise a bulletted list).
- [x] Organisaties FKs (all 4) should be readonly in the CMS edit screen.
- [x] Deactivate language buttons should be removed in the CMS
- [x] Fix incorrect word: "SDG voor de Harderwijk". The "de" should not be there.
- [x] When you logout, the logout screen has no message bar so the logout message is shown when you login (from the queue).

**Verify**

- [x] Datepicker seems not to work in Docker builds
