### ISSUE TITLE
[US-15] Als Gemeente Redactie wil ik aan kunnen geven op welke locatie het product afgenomen kan worden zodat de burger naar het juiste loket wordt verwezen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#16]
Per gemeente kan het verschillen waar men voor bepaalde producten heen moet om de aanvraag te doen.
Het is nog onduidelijk hoe dit op de Nationale Portalen gaat werken

**Acceptatiecriteria** :
* bij elk product kan aangegeven worden op welke locatie het afgenomen kan worden.
* Indien een gemeente slechts 1 locatie kent dan wordt deze voorgeselecteerd
* Wanneer een product wordt opgevraagd dan worden de gekoppelde locatie geleverd

**Tasks**

* [x] Add location edit form on edit page for locations (see screenshot)
* [x] Add read-only version of the edit form on detail page (see screenshot)
* [x] If there is only 1 location, by default make the first location checked.

![image](https://user-images.githubusercontent.com/96970/137579002-30c305b1-7421-4213-9d02-970051f15747.png)
