### ISSUE TITLE
Contactgegevens gemeente Haarlemmeer passen niet

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#176]
Contactgegevens gemeentebalie Schiphol van de Haarlemmeer passen niet.
https://haarlemmermeergemeente.nl/taak/contact-openingstijden-en-afspraak-maken

Wat past niet
- haarlemmermeer heeft geen e-mail adres, maar een contactformulier
   - check op geldig e-mail adres verhindert creatief invullen web-adres formulier
- Gemeentebalie Schiphol heeft geen adres
   - De gemeentebalie Schiphol is op de luchthaven Schiphol in aankomsthal 2. De balie is vlakbij de baggage reclaim en zit naast Segafredo. 
- Openingstijden op afspraak (voor schiphol)
   - Op afspraak kan niet voor of achter de tijd getypt worden.
   - Het vereiste formaat voor openingstijden wordt niet getoond

**Tasks**

* [ ] Add description field (named: "Aanvullende informatie") to location to allow free text. Also add this field to the API.

**Out of scope for now**

* [ ] Add new field to org: contact_url
* [ ] Allow frontend to fill both contact email and contact url.
* [ ] Show sticky page warning when contact email AND contact url are both empty.
* [ ] ... todo: allow free field for times, or boolean field for appointment? a description field maybe? @FrankLieuwen

**Comment by joeribekker** [comment]
Heren, we hadden al "Openingstijden opmerking" via dit ticket: https://github.com/maykinmedia/sdg-invoervoorziening/issues/236

Ik vermoed dat dit ticket daarmee gesloten kan worden.
