### ISSUE TITLE
[US-18] Als Gemeente Redactie wil ik een referentietekst van een product kunnen gebruiken (referentieproduct)

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#19]
... zodat ik ontzorgd word, zeker weet dat ik voldoe aan de SDG en de specifieke teksten van gemeenten waar mogelijk uniform zijn

Referentieteksten worden opgesteld door de gezamenlijke redactie. Deze teksten kunnen overgenomen en/of aangevuld worden met gemeentelijke informatie.

**Acceptatiecriteria** :
* De gebruiker heeft voor elk product de mogelijkheid voor de referentietekst te kiezen.

**Tasks**

* [x] The checkbox described in #13 should suffice.
* [x] On the product edit page, add link/button to reset the the current text in the textarea to the reference text.

![image](https://user-images.githubusercontent.com/96970/130628915-2ceb560d-77c2-45c8-91ac-dac071072bb8.png)

**Verduidelijk**

* [x] Is punt 2 nodig/gewenst? Yep
