### ISSUE TITLE
Create a stable product flow from UPN to Standard product text

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#194]
We should create a lasting flow for new products and make sure they are picked up by SDG and the SDG admin so they can be followed up.

**Tasks**

* [x] Add fields to Catalog: autofill (boolean, default=False), autofill_upn_filter (array of strings, default=[])
* [x] Schedule the periodic (daily) import of UPN, Informatiegebieden, Overheidsorganisaties, and the new UPN-SDG-Informatiegebieden (#116). Typically use Celery Beat for this that calls the management commands as task.
* [x] Upon creation of a new UPN...
* [x] 1. Get all catalogs marked as reference catalog, that have `autofill=True`
* [x] 2. Check if the UPN has the `autofill_upn_filter` that matches all (so it's an AND-list) strings of the found catalogs. Typically, these strings are "gemeente" and "SDG" for our scope.
* [x] 3. If the UPN matches a catalog that has the proper `autofill_upn_filter`, create an (empty) `GenericProduct` and (empty) `SpecificProduct` (including productversion, localized for each language, etc.) in that catalog.

Expected result is an automated, fully filled, SDG catalog for VNG that acts as a reference catalog - so that it can be filled from the CMS (and nothing needs to be done in the admin).

NOTE: The GenericProducts are empty and can only be managed from the admin. This is a temporary solution until we can fill the GenericProduct from an external API.
