### ISSUE TITLE
Project opstarten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#2]
**Tasks**

* [x] Setup the repository (@joeribekker)
* [x] Create project board (@joeribekker)
* [x] Create new project from default-project, named `sdg` (ie. I want to see `from sdg.accounts.models import User`)
* [x] Commit project to this repo
