### ISSUE TITLE
Als redacteur wil ik kunnen kiezen tussen de doelgroepen burger- of ondernemer

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#201]
Only do after #217 

**Tasks**

* [x] Replace language "name" with flag. Show grey if language present, show colored when datumCheck is filled.
* [x] Use Dutch and British flags for languages
* [x] Add doelgroep to detail/edit page as a field
* [x] Add doelgroep to list item, after the flags
* [x] Add filter (checkboxes) for: "Voor burgers" "Voor bedrijven" which filter on doelgroep.

*Verduidelijkt met Frank*

**Original ticket**

opdat ik mijn tekst kan richten op de juiste doelgroep.

De invoervoorziening weet of een of een product een burger en/of ondernemerproduct is door het inlezen van de UPL (zie #116)

De invoervoorziening toont aan de redacteur nu niet de doelgroep. Nog te bepalen waar de doelgroep getoond gaat worden. Bijvoorbeeld:
- als filter in de productenlijst. Een redacteur kan dan alle burger, ondernemer of alle burger én ondernemer producten zien.
- bij de generieke tekst
- in de producttitel
   - onroerende zaakbelasting (ozb) voor **burgers**
   - onroerende zaakbelasting (ozb) voor **ondernemers**

**Comment by MiekeBos** [comment]
Kunnen we de term "burger" vervangen door "inwoner"? Niemand is meer een burger, iedereen is een inwoner.

**Comment by joeribekker** [comment]
@MiekeBos Kan je daar een nieuw issue voor aanmaken?
