### ISSUE TITLE
Als redactie wil ik op de wijzigen pagina zien wat mijn huidige tekst is en wat de standaardtekst is...

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#203]
... zodat ik deze goed kan wijzigen.

**Tasks**

* [x] When a new specific product is created, please fill it with all the standard texts for this product (currently, we create an empty specific product)

_On the product edit page:_

* [x] ~Remove "copy standard text" link/feature~
* [x] Don't show the "edit" fields right away. Show the non-edit fields (like on the detail page) instead.
* [x] Add new link/feature to change the non-edit field into an edit field (hide non-edit, show edit) , called "Aanpassen".

![image](https://user-images.githubusercontent.com/96970/140751345-e4444d7a-e563-4ce3-b7b2-44ec12e28d74.png)
