### ISSUE TITLE
Als redactie wil ik een beter navigeerbare producten catalogus

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#204]
The idea is to make the layout more consistant and have more navigation options.

Site structure:

* homepage ``/``  (organisation overview, each org links to a catalog - see next item) 
  * catalogs ``/organisation/1/catalogs/``  (shows the products in each catalog, for specific organisation)
    * view product ``/organisation/1/catalogs/1/product/1/``
    * edit product ``/organisation/1/catalogs/1/product/1/edit/``
  * locations ``/organisation/1/locations/``
  * users ``/organisation/1/users/``

**Tasks**

* [x] Update site structure to the layout shown above.
* [x] The subtitle should always be the organisation name (example: Gemeente Harderwijk); except for the homepage which has no subtitle.
* [x] Remove the location container at the top from the catalog overview page.
* [x] If a user has only 1 organisation, redirect from the home page to the organisation page (99% of the time for users). If a user has more than 1 organisation, do not redirect
* [x] If a user has more than 1 organisation, show a "switch" icon next to the organisation name in the subtitle. This icon links to the homepage. -- switch icon: https://fontawesome.com/v5.15/icons/exchange-alt?style=solid
* [x] Decrease the height of the header
* [x] Except for the homepage, there's always 3 tabs visible: Catalogs, Locations, Users; They should be active if you are at that page or a subpage. They can link to the existing pages (for locations this is the edit page for locations).
* [x] Add a crumblepath below the tabs, following the site structure
* [x] Add pagetitle. This title should always say what is shown on this page: (examples: SDG Catalog; Product X; Edit product X;

![image](https://user-images.githubusercontent.com/96970/140754576-aefdeea7-06e5-4222-8cd4-9a8d0ce369d7.png)

![image](https://user-images.githubusercontent.com/96970/140968130-b9702906-c350-49d9-a271-8cf6448fd9b0.png)

**Example (left image)**

* **Site title**: SDG
* **Subtitle**: Gemeente Harderwijk
* **Page title**: SDG Catalogus # NOTE: on the catalogs page, it can show multiple page titles (=catalog name) since we show all catalogs below eachother.
* **Crumblepath**: Home > Gemeente Harderwijk > Catalogi

**Example (right image)**

* **Site title**: SDG
* **Subtitle**: Gemeente Harderwijk
* **Page title**: Paspoort aanvragen
* **Crumblepath**: Home > Gemeente Harderwijk > SDG Catalogus > Paspoort aanvragen
