### ISSUE TITLE
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder een notificatie/alert ontvangen via de mail dat er wijzigingen zijn

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#213]
Bram Dijkshoorn  •  28 okt
Namens DPC en DOP:
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder:
· een alert ontvangen via de mail dat er wijzigingen zijn

**Tasks**

* [x] Change user list page to add "wijzigen" for the logged in user
* [x] Make sure if you change your own details, in user-edit page, you cannot change your role
* [x] Add option to user-edit page to receive text changes emails.
* [x] Add setting SDG_MAIL_TEXT_CHANGES_EVERY_DAYS=7 (default, but read from environment)
* [x] Create e-mail with table with changes (see the notifications page) that includes the changes in the last `SDG_MAIL_TEXT_CHANGES_EVERY_DAYS` days
* [x] Add field `mail_text_changes_last_sent` to singleton `Config` model that keeps track when the last mail was sent.
* [x] Create celery task that runs daily and checks if `Config.mail_text_changes_last_sent < today + SDG_MAIL_TEXT_CHANGES_EVERY_DAYS`
* [x] Send the email to all users that have "receive text changes emails"=True
* [x] Add datamigration to set the "receive text changes emails" to True for redacteuren and beheerders.

**Comment by joeribekker** [comment]
Blocked by #256 en #227

**Comment by joeribekker** [comment]
We hebben nu de "(!) Controle nodig" functie (een filter). Is het nodig dat er een mail gestuurd wordt?

Wie is de "beheerder" in dit geval (omdat het ticket door DOP en DPC zijn ingeschoten)?

Als we dit ticket oppakken stel ik me voor dat we dagelijks controleren en maximaal dagelijks een mail sturen waarbij alleen maar staat dat er wijzigingen zijn (geen lijst met wat er is gewijzigd) + link naar SDG invoervoorziening.

**Comment by joeribekker** [comment]
@FrankLieuwen Wat vind jij van bovenstaande punten?

**Comment by FrankLieuwen** [comment]
We hebben nu de "(!) Controle nodig" functie (een filter). Is het nodig dat er een mail gestuurd wordt?
**- Ja, met maximaal 1 per dag zoals hieronder aangegeven**

Wie is de "beheerder" in dit geval (omdat het ticket door DOP en DPC zijn ingeschoten)?
**ik lees hem als redacteur, gezien de afzender van het verzoek**

Als we dit ticket oppakken stel ik me voor dat we dagelijks controleren en maximaal dagelijks een mail sturen waarbij alleen maar staat dat er wijzigingen zijn (geen lijst met wat er is gewijzigd) + link naar SDG invoervoorziening.
**eens**

**Comment by joeribekker** [comment]
Deze heeft het niet gered in sprint 6. Opnieuw prioriteren in latere sprints.

**Comment by mrtn78** [comment]
Wieke: Bij het wijzigen van de standaardteksten moet een popup komen waarin de wijziging van de standaardtekst wordt toegelicht.
Bijvoorbeeld:
"comma toegevoegd"
"jaartal bijgewerkt"
"tekst herschreven op basis van wetswijziging"
"tekstuele wijzigingen om de leesbaarheid te verbeteren"

Rob & Douwe: ook algemene notificaties opnemen wanneer het systeem is gewijzigd

**Comment by mrtn78** [comment]
Prio Hoog ivm de vele vragen op dit moment over wijzigingen

**Comment by mrtn78** [comment]
zie ook https://github.com/maykinmedia/sdg-invoervoorziening/issues/617#issuecomment-1238187278

**Comment by joeribekker** [comment]
De mail functionaliteit uit dit ticket is nooit gerealiseerd. Dit ticket is gesloten omdat in #617 een pagina is gemaakt met de recente wijzigingen. Volgens mij was dit zo besproken maar ik lees dat helaas niet terug.

**Comment by joeribekker** [comment]
> @mrtn78 Ik verwacht dat je me per ongeluk hier genoemd hebt want ik heb nog nooit van dit project/organisatie/whatever gehoord.

Foutje. Ik verwijder even alle referenties @Wieke zodat je er geen last meer van hebt.

**Comment by RobbieZ69** [comment]
De standaard tekst die we hebben opgesteld voor Standaard e-mail notificaties  

Subject: Aanpassing in tekst SDG-invoervoorziening 


Beste <voornaam>, 

Je krijgt deze mail omdat jij een account hebt van de SDG-invoervoorziening. Recent is er een aanpassing geweest in de teksten in de invoervoorziening. Het gaat om de volgende wijziging(en): 

<invoegen> 
<invoegen> 
Etc.  

Mogelijk moet je naar aanleiding hiervan je eigen gemeentetekst ook aanpassen. Of misschien moet je jouw tekst opnieuw publiceren zodat bovenstaande wijziging zichtbaar is op de nationale portalen.  

In de invoervoorziening zie je om welke aanpassing het gaat en of er van jou een actie nodig is.  

<link naar invoervoorziening>  

Alvast bedankt voor de medewerking! 

 

SDG-team 
VNG
