### ISSUE TITLE
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder bij het inloggen in de invoervoorziening een lijst zien van wijzigingen

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#214]
Bram Dijkshoorn  •  28 okt
Namens DPC en DOP:
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder:
· bij het inloggen in de invoervoorziening een lijst zien van wijzigingen

**Tasks**

* [x] Add field `internal_remarks` to productversion model (blank=True): Dutch label: "Opmerkingen"; Dutch help-text: "Interne opmerkingen die niet zichtbaar zijn buiten deze omgeving." These remarks do not need to be language/localized specific.
* [x] Expose field in CMS, in "Algemene gegevens":
   ![image](https://user-images.githubusercontent.com/96970/193549372-ad9c2c5d-eb36-439b-abb1-75017fcdaf57.png)
* [x] ~Record the changed fields in the model.~ NOTE: Let's not do this right now. People can indicate this in the internal remarks section.
* [x] Create new page to show all notifications. This page should ONLY show "notifications" from all reference products (and published versions of it - not concept versions). In timeline order.
* [x] Add menu item to above page, that is visible at all times (not just when an organization is selected).
   ![image](https://user-images.githubusercontent.com/96970/193550728-8125a7e0-5986-4ba5-be25-0b454d7d3a24.png)
* [x] On the history section, add the notifications from the "reference products" for that product. Basically, this is a subset of the page created above, just for this product - mixed with the updates from the user for this product: 
   ![image](https://user-images.githubusercontent.com/96970/193552192-4f9e2d24-7d61-45e0-ae6d-63bf5c16d962.png)

**Comment by joeribekker** [comment]
Ook hier voldoet volgens mij het "(!) Controle nodig" filter?

@FrankLieuwen wat vind jij?

**Comment by FrankLieuwen** [comment]
Hier voldoet het "(!) Controle nodig" filter

**Comment by joeribekker** [comment]
Deze heeft het niet gered in sprint 6. Opnieuw prioriteren in latere sprints.

**Comment by mrtn78** [comment]
deze heeft een relatie met issue #350

**Comment by mrtn78** [comment]
Voor nu is de eerste prio het toevoegen van de mogelijkheid om na het publiceren van een standaard tekst een notificatie toe te voegen aan de 'opslaan actie'. Ik verwacht een popup met een schermpje waarin wordt gevraagd of je na het opslaan en publiceren ook een notificatie wilt opslaan die wordt getoond aan alle gebruikers. Voorbeeld:

Wil je de publicatie van deze wijziging toelichten in een notificatie aan de gebruikers? 
[ ja / nee ]
[indien ja: ]Omschrijf de wijziging van de standaardtekst. Bijvoorbeeld:
"Spelling gecorrigeerd"
"jaartal bijgewerkt"
"tekst herschreven op basis van wetswijziging"
"tekstuele wijzigingen om de leesbaarheid te verbeteren"
