### ISSUE TITLE
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder  in de standaardteksten kunnen zien wát er is gewijzigd

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#215]
Bram Dijkshoorn  •  28 okt
Namens DPC en DOP:
Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder:
· in de standaardteksten kunnen zien wát er is gewijzigd

**Tasks**

* [x] Figure out how to show differences between previous and current "standaardtekst".
* [x] Show like commits (red/green) between latest published version and previous published version
* [x] Show a small legend: Red=Published version 2020-01-01, Green=Published version 2021-01-01

**Ugly mock**

![image](https://user-images.githubusercontent.com/96970/144838316-25df5106-a253-4c9b-944e-14e3a77e527c.png)

*eye added in top left corner of the dark gray area, as a toggle*

**Comment by joeribekker** [comment]
Afgestemd met Frank
