### ISSUE TITLE
Als redactie wil ik zoeken en filteren binnen producten in de catalogus

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#217]
Should be done after #204 

**Tasks**

* [x] Don't collapse other items when you expand another (this means you can expand more than 1 category)
* [x] Below the page title (catalog name), add a search field that **filters** through a product data-attribute that (currently) only contains the product name (JS filter). All non-matching products should be hidden, all categories should be expanded.
* [x] On the right of the search field, there should be an option to collapse/expand all categories
* [x] Below the search field, add checkboxes to filter on product status. These statusses should match the legend icon list.
* [x] The above should work PER CATALOG, so there's a search field + filter for each catalog, below each catalog name.

![image](https://user-images.githubusercontent.com/96970/140767631-67dfe8c8-62d1-4027-bc3a-dc8df2e2fbbe.png)

![image](https://user-images.githubusercontent.com/96970/140968311-c1b3bc51-f226-4da2-9f5f-ad7b1d2a5780.png)
