### ISSUE TITLE
Als redactie wil ik helder hebben wat/wanneer wordt opgeslagen en/of gepubliceerd wordt

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#219]
**Tasks**

Tasks are all related to the view/edit product page (where appropriate only edit or view).

* [x] Add global product info fields at the top: Beschikbaar, Locaties, UPN (you did something similar in #193 )
* [x] Style the NL-EN-tabs to fit the gray content area. The idea is that these tabs indicate a section WITHIN the product page so that it does not seem that it concerns the entire product, but just the generic/specific texts.
* [x] Replace the current radiobuttons and save buttons with: Publication date field (always shown), "Opslaan en publiceren"-button, "Opslaan als concept" button, "Annuleren" button.
* [x] Publication date should be prefilled with the existing date if stored.
* [x] Publication date is mandatory if pressing the "Opslaan en publiceren" button. Give an error if not provided.
* [x] Process issues from the current design in the screenshot below.

## Current design

![image](https://user-images.githubusercontent.com/96970/145095932-90980f65-4648-460b-b79c-f3a735f71386.png)

## Desired design

![redesign-product-page](https://user-images.githubusercontent.com/96970/141096908-7591bbc3-0219-4afb-b553-afd269d6ad4a.png)

**concept idea archived**
  * "als nieuwe versie en publiceren" if the the product is saved as a new version (logic already present in the view/form code)
  * "en publiceren" if the product the product will be saved in the same instance (logic already present in the view/form code)

## Mockup

![image](https://user-images.githubusercontent.com/96970/140782510-c60c0de4-53ea-4318-a242-03dfc1dbdbe1.png)
