### ISSUE TITLE
[US-21] Het is wenselijk dat de invoervoorziening ook mogelijkheden of functies krijgt waarmee de ingevoerde content in de verschillende formats

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#22]
... en verschillende stylesheets kan worden gevisualiseerd (als test) voordat men definitief publiceert.

**Verduidelijking nodig**

Is dit echt nodig? Wij gaan niet over hoe e.e.a. eruit komt te zien op de NNP. We hebben al wel een WYSIWYG-editor waardoor de opmaak al wel in basis-vorm getoond wordt.

**Tasks**

* [x] Create small design for preview
* [x] Add preview page (pretty empty)
* [x] Add preview button to detail/edit page

API to give concepts is done in another ticket.

**Comment by FrankLieuwen** [comment]
uiteindelijke vorm ene weergave is pas zichtbaar op NP, mogelijkheid onderzoeken of concept onderdeel moet gaan uitmaken van API

**Comment by FrankLieuwen** [comment]
@markbacker ik geef even wat context

Vanuit de feedback op sprint 3 is de vraag gekomen om een preview van de invoer voordat deze wordt gepubliceerd (een preview van de concept tekst dus). Nu heeft de invoervoorziening geen frontend dus het tonen kan niet vanuit deze voorziening worden gefaciliteerd, de frontend 'woont' immers bij de NP.

Nu is de vraag dus of de betreffende concept tekst in de API moet worden opgenomen zodat aan de NP kant een preview kan worden getoond. Betekent dus wel er aan de frontend kant ook rekening moet worden gehouden met het ontsluiten en tonen van de preview.

**Comment by markbacker** [comment]
Duidelijk. Tot nu heb ik me eigenlijk niet zo beseft dat we nu alleen in een preview voorzien voor gepubliceerde teksten en niet voor concepten. Daar is weinig pre aan.

Uitgangssituatie
- de invoervoorziening heeft en krijgt geen functionaliteit voor het tonen van een preview (althans niet anders dan het invoerformulier met WYSISWYG editor)
- de SDG product API stelt gepubliceerde teksten beschikbaar

Te onderzoeken oplossing
- de SDG product API stelt ook concept teksten beschikbaar (de laatst bewerkte versie)
- de portalen maken een speciale ingang/extra parameter voor redacteuren om concepten te previewen

Ik ga de vraag aan de portalen voorleggen.

**Comment by joeribekker** [comment]
> Tot nu heb ik me eigenlijk niet zo beseft dat we nu alleen in een preview voorzien voor gepubliceerde teksten en niet voor concepten.

Ter aanvulling. We voorzien helemaal niet in een "preview" functie (gepubliceerd of concept) anders dan de WYSYWIG-editor. In de WYSYWIG-editor kan je zowel concepten als gepubliceerde teksten "previewen".

Definitie van preview is wat ambigu hier, maar wij **kunnen geen preview tonen van hoe het op de portalen komt te staan**. Dit kan alleen een feature zijn van de portalen zelf, en als ze dat hebben kunnen we daar iets voor maken om bij te helpen.

**Comment by markbacker** [comment]
In de onderstaande user story is de term previewen vervangen door raadplegen. In deze vorm ligt dit nu voor bij het ondernemersplein.

user story:
_Als gemeente redacteur wil ik een concept specifieke tekst kunnen raadplegen op het Nationale Portaal, opdat ik de weergave kan controleren voordat ik de tekst publiceer_

Voor de oplossing is het nodig dat:
-	conceptteksten door de API beschikbaar worden gesteld
-	een gemeente redacteur via het portaal de conceptteksten kan opvragen en bekijken.
-	Een burger of ondernemer via het portaal geen toegang heeft tot de conceptteksten.

Een mogelijke oplossing kan zijn dat de invoervoorziening bij een concepttekst portaal-URL met een unieke parameter genereert, die toegang geeft tot die éne concepttekst.
