### ISSUE TITLE
[US-30] Als Gemeente redactie wil ik de generieke teksten van de NP kunnen raadplegen, zodat ik de specifieke tekst hierop goed aan kan laten sluiten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#23]
Of raadpleegbaar met een API
Of redactie portalen werkt in invoervoorziening

**Acceptatiecriteria** :
* van een product wordt de Generieke tekst getoond indien aanwezig. ~Indien er geen generieke tekst beschikbaar is dan wordt een waarschuwing getoond~

**Tasks**

* [x] Add the GenericProduct fields as readonly above the editable fields of the SpecificProduct in the cms page
* [x] ~If the reference product does not exist (anymore), show warning in the cms page ("Dit product is van de productenlijst verwijderd. Uw product is nog zichtbaar omdat u deze in het verleden heeft toegevoegd aan uw catalogus maar zal niet meer getoond worden op de Nationale Portalen.")~
* [x] ~If there are is no reference_product.generiek_product, show warning in the cms page ("Dit product heeft geen generieke product teksten") and then, don't show the generic fields.~

![image](https://user-images.githubusercontent.com/96970/130629872-66572947-9e63-4ad5-a5dd-1d16181eb848.png)

Meldngen taken naar nieuw ticket verplaatst.
