### ISSUE TITLE
[US-31] Als Gemeente Redactie wil ik een waarschuwing wanneer de generieke tekst is gewijzigd zodat ik de aanvullende teksten daarop aan kan passen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#24]
**Acceptatiecriteria**:

wanneer de generieke tekst is gewijzigd krijgt de gemeente een waarschuwing m.b.t. dit product dat de aanvullende teksten opnieuw beoordeeld moeten worden.
De actualiteitseis van de waarschuwing is laag. Een oplossing kan zijn dat dagelijks wordt opgevraagd welke teksten gewijzigd zijn

**Tasks**

* [ ] @markbacker overweegt een "laatste_wijzigingsdatum" / "publicatie_datum" te laten opnemen bij Generiek Product, per taal.
* [ ] Always color flags for languages (no logic anymore)
* [ ] Add new filter to check changes in generic text (like with standard texts)

@markbacker Helaas, het !-icoon gaat over wijzigingen in de standaardtekst, en niet over de generieke tekst. Nog een icoon toevoegen? Ook moet het IM aangepast worden want we hebben een publicatie datujm nodig.

**Comment by markbacker** [comment]
**Afweging**:
Is een melding voldoende? 
- Als het een significante wijziging is, dan stelt de GGR een mail op met daarin reden en benogide actie van de gemeenteredacties. 
- bij een kleine wijziging (typo, verduidelijking tekst, etc.. ) dan wordt geen mail gestuurd en alleen de melding getoond. Hier is een diff om te laten zien wat gewijzgd is wel gewenst.

Het informatiemodel kent voor de generieke tekst het attribuut DatumCheck
> **Datum laatste check nationale tekst**
> De informatie over het product kan worden gewijzigd en gecontroleerd op actualiteit (gecheckt). De Nationale portalen houden bij wanneer de informatie voor het laasts is 'gecheckt'.  Deze datum wordt op het portaal getoond

Voor nu gaan we ervan uit dat de portalen pas een tekst publiceren als deze gecontroleerd is. Ik ga navragen of er significante wijzigingen kunnen zijn, zonder dat de DatumCheck veranderd is.

Volgens mij moeten we dit getrapt maken. De GGR is de poortwachter die beoordeeld welke wijzigingen in de generieke tekst impact hebben op de specifieke teksten:
1. als de generieke tekst gewijzigd is (DatumCheck > DatumWijziging tekst in referentiecatalogus), leidt dit tot een melding op de standaardteksten. De GGR beoordeelt de wijziging en wijzigt eventueel de standaardtekst.
2. als de standaardtekst gewijzigd is (DatumWijziging tekst in referentiecatalogus > DatumWijziging tekst in gemeentecatalogus) toon melding aan gemeenteredactie.

De melding is het gele uitroepteken "De standaardtekst is gewijzigd, controleer uw specifieke tekst"

**Comment by FrankLieuwen** [comment]
Melding binnen invoervoorziening is afdoende, het uitroepteken verschijnt bij kleine wijziging en wordt door redacteur afgevinkt als tekst is aangepast

**Comment by FrankLieuwen** [comment]
Wordt uitgewerkt in GGR workflow, waarschuwing wordt gedekt door standaardteksten
