### ISSUE TITLE
Refactor creation of generic products from UPNs

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#244]
In issue #194, it states:

> 2. Check if the UPN has the autofill_upn_filter that matches all (so it's an AND-list) strings of the found catalogs. Typically, these strings are "gemeente" and "SDG" for our scope.
> 3. If the UPN matches a catalog that has the proper autofill_upn_filter, create an (empty) GenericProduct and (empty) SpecificProduct (including productversion, localized for each language, etc.) in that catalog.

This is not implemented as expected. The filter should look at the boolean fields present in the `UniformeProductnaam` model.
Second, it should not only work for existing `UniformeProductnaam` instances. Just always check if the generic product already exists, if so, skip. 

**Tasks**

* [x] Change the `UniformeProductnaam.save` method so the `autofill_upn_filter` is matched against the boolean fields (case insensitive). The value `["sdg", "gemeente"]` should match when both `UniformeProductnaam.gemeente=True` and `UniformeProductnaam.sdg=True`.
* [x] Change the save in such a way, it always creates the generic/specific product, even if the `UniformeProductnaam` already existed (unless te generic/specific product already exist in that catalog).
* [x] Run the import task, and check if products are created as expected in both the admin and the frontend (I noticed duplicates in the frontend)

I know the frontend will perform 5000 queries on the catalog page, we will optimize this in another ticket!

![image](https://user-images.githubusercontent.com/96970/143773745-07c22ffa-85f2-44bc-a8d7-bc48e0188414.png)
