### ISSUE TITLE
[US-32] Als gedeelde redactie wil ik voor ieder product de referentietekst kunnen beheren, opdat gemeenten deze kunnen hergebruiken

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#25]
This ticket is about reference products (Standaard*-models) that are managed by a user with the permission `is_global_redacteur`.

**Tasks**

* [x] Add detail page view/template for a product (field name, field help text and field value)
* [x] Last column (see screenshot) can be `datum_wijziging` date
* [x] Show all available languages as tab. Each tab includes the product in the selected language.
* [x] Clicking the yellow "Wijzigen" button shows an edit page, like the 2nd screenshot, with a textarea/input/markdown widget for each field. There's a save button at the bottom.

NOTE: Deactivate languages (as shown in the screenshot) are not part of this ticket.
These changes can be saved directly, no need to take any publishing (future) date into account or anything. The behaviour is simple and plain.

![image](https://user-images.githubusercontent.com/96970/130623336-54e27796-8f31-4fda-80a5-b17f11d74c09.png)

![image](https://user-images.githubusercontent.com/96970/131361676-94d7925e-5db9-4b92-8d92-b815aea38fb0.png)
