### ISSUE TITLE
Add small convience features to the API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#274]
Some refactoring to make the API more usable by organisations that use the government wide layer of identifications, rather then our own identifications.

**Tasks**

* [x] Add new `ProductReferenceSerializer` that exposes a small subset of the fields for a `Product`, used in references to a product. The fields are: `url`, `upnUri`, `upnLabel`
* [x] Use `ProductReferenceSerializer` in `catalog.producten` and `product.gerelateerdeProducten`
* [x] Add new `OrganisatieReferenceSerializer` that exposes a small subset of the fields for a `Organisatie`, used in references to a organisation. The fields are: `url`, `owmsIdentifier`, `owmsPrefLabel`
* [x] Use `OrganisatieReferenceSerializer` in `catalogi.organisatie`, `locatie.organisatie` and `product.organisatie`
* [x] Add the query param `organisatieOwmsIdentifier` and `organisatieOwmsPrefLabel` to `catalog-list`, `location-list` and `product-list`.
