### ISSUE TITLE
Create seperate generic/specific products if a UPN is meant for more than 1 doelgroep

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#275]
@markbacker Wil je beschrijven hoe deze logica zou moeten werken?

| UPN | Overheid | SDG code | Burger | Bedrijf |
| --- | --- | --- | --- | --- |
| kinderopvangtoeslag | Gemeente | E1;G1 | X | |
| omgevingsvergunning | Gemeente, Wachterschap, Provincie, Rijk | N1 | X | X |
| onroerendezaakbelasting (ozb) | Gemeente | D2;L5 | X | X |

Gegeven bovenstaande UPN, tot welke Generieke en Specifieke producten moet dit leiden?

**Tasks**

NOTE: Here I assume the logic is based on the UPL import, but the SDG-codes are ALSO present in the UPL-SDG import! If it makes more sens to do task 2 in that step, please do that.

* [x] Detect the SDG-code in the UPL import; Store the SDG-codes in an array field
* [x] If the SDG-code is in the range A-I, the "doelgroep" is "burger". The range J+ sets the "doelgroep" to "bedrijf". We can ignore the "Burger", "Bedrijf" columns!
* [x] Add unique constraint on `doelgroep+upn`
* [x] Create a Generiek AND Specific product for each "doelgroep".
* [x] Rename "doelgroepen" choices: "burger" -> "eu-burger", "bedrijf" -> "eu-bedrijf"
* [x] Make sure that if there are 2 products created, 1 for "eu-burger" and 1 for "eu-bedrijf", that they both belong to the correct thema/informatiegebied
* [x] If a single product belongs to multiple themes (so, a product with doelgroep=eu-burger for example), it can pick whatever theme for now. No need to change it to a m2m.
* [x] Move the doelgroep field to the generic model

Note: Codes are themes :)

**Comment by joeribekker** [comment]
@mrtn78 zegt:
A-I = burger, J+ = Bedrijven

**Comment by mrtn78** [comment]
idd. zie ook https://eur-lex.europa.eu/legal-content/NL/TXT/?uri=CELEX%3A32018R1724
