### ISSUE TITLE
Make the detail page similar to the edit page

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#295]
There are confusing differences between the edit page and the detail page. The edit page is leading for the layout!

![image](https://user-images.githubusercontent.com/96970/146923106-b3884490-3e07-46f2-a355-fbcc5f283eba.png)
![image](https://user-images.githubusercontent.com/96970/146924130-8dd3b18b-a7fc-4061-a09e-4999766ccb82.png)

**Tasks**

* [x] The order of the fields in the detail page should be the same as the edit page (Aanwezig, Aanwezig toelichting, Lokaties, Doelgroep)
* [x] THe field **names** on the detail page should be the same as the edit page.
* [x] The `product aanwezig` field value should be: ja, nee, onbekend (currently: null, true, false)
* [x] The (i)-icons are missing from the edit page, please add them there
* [x] Locations in the detail page should be moved to the top (like the edit page) and look similar to doelgroep (- burgers)
* [x] Revisions (only shown on detail page - as it should) should be positioned below the border, aligned left.
