### ISSUE TITLE
[US-52] Als hoofdbeheerder van een gemeente redactie wil ik de toegang voor redacteuren kunnen beheren

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#33]
..., zodat ik controle heb wie productbeschrijvingen kunnen wijzigen voor mijn gemeente

**Acceptatiecriteria** : het accountbeheer moet voldoen aan de eisen van de BIO, bijvoorbeeld dat het mogelijk moet zijn accounts te verwijderen.

**Tasks**

* [x] Add CMS page/view/template to see the `request.user->role->organizations` (can be multiple). For each organization, show a list of users with their role (see mockup below)
* [x] Add a delete action to remove users (ie. remove their Role, not the user itself). Only a beheerder **of the same organization** can see this action, and therefore only a beheerder can delete other users that belong to the organization that the user is a "beheerder" of.
* [x] The logged in user cannot delete itself.
* [x] Allow a beheerder to create users. A beheerder can only create users for the organziations they are "beheerder" for. A new user can be a "beheerder" or a "redacteur" (see 2nd mockup below)
* [x] Upon creation of a new user, an invite is sent to setup the password. This invite should be reflected in the list of users (see mockup, "Mark Mah"

**Mockup: List of users**

Gebruikers
=======

Amsterdam
-------------

| Naam | Rol | Acties |
| --- | --- | --- |
| John Doe | Beheerder |  |
| Martin Moo | Redacteur | [Verwijderen](#) |
| Jane Bar | Redacteur | [Verwijderen](#) |

[Nieuwe gebruiker toevoegen](#)

Harderwijk
-----------

| Naam | Rol | Acties |
| --- | --- | --- |
| Frank Foo | Beheerder |  |
| John Doe | Redacteur |  |
| *Mark Mah* | Redacteur | Uitnodiging verstuurd.

_NOTE: Users cannot delete themselves. John Doe is logged in in this mockup. John Doe is "beheerder" of Amsterdam and can delete Jane Bar and Martin Moo. John doe is also a "redacteur" of Harderwijk. Since John Doe is not "beheerder" of Harderwijk, he cannot delete Frank Foo. John Doe can not see/use the "Nieuwe gebruiker toevoegen" action for Harderwijk._

**Mockup: Add new user**

Nieuwe gebruiker toevoegen
=================

U staat op het punt een nieuwe gebruiker toe te voegen voor de organisatie *Amsterdam**.

| - | - |
| --- | --- |
| E-mail | ___________________________ |
First name | ___________________________ |
Last name | ___________________________ |
Role | (x) Redacteur ( ) Beheerder |

De gebruiker ontvangt na het opslaan een uitnodiging om een wachtwoord in te stellen. Hiermee wordt ook het e-mailadres gevalideerd.

[Opslaan](#)
