### ISSUE TITLE
Als functioneel beheerder wil ik zelf de labels en tooltips kunnen aanpassen

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#349]
opdat onduidelijkheden snel en zonder kosten kunnen worden opgelost

**Tasks**

Basically, all labels and tooltips need to be configurable for the CMS edit/detail pages. It's a global thing :)

* [x] Add Django Solo model: LabelConfiguration
* [x] Add all labels and tooltips (from the detail/edit product page - so for Generic and Specific fields) as field on the model, so they can be changed/configured
* [x] Add admin to configure this in the admin
* [x] Use the configured labels and tooltips instead of the hardcoded labels and tooltips on all form fields.

**Comment by markbacker** [comment]
@FrankLieuwen wil jij deze user story bekijken. Als je je erin kan vinden, wil je deze dan aan Joeri toekennen. 
Joeri gaf aan hier deze sprint ruimte voor te hebben.
