### ISSUE TITLE
[US-54] Als VNG functioneel beheerder wil van een gemeente een hoofdbeheerder toegang kunnen geven

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#35]
..., opdat de gemeente redacties zelf de redacteuren kunnen toevoegen

**Acceptatiecriteria** : het accountbeheer moet voldoen aan de eisen van de BIO, bijvoorbeeld dat het mogelijk moet zijn accounts te verwijderen.

**Tasks**

* [x] Add m2m relation between `User` and `LokaleOverheid` with a through-model `Role`
* [x] Users that can only access the CMS are NOT staff users.
* [x] On the `User` model, add a `is_redacteur` field. This field indicate people that can edit the reference texts.
* [x] On the `Role` model, add a `is_beheerder` and `is_redacteur` field. These fields define the role of the user for a specific `LokaleOverheid` organization.
* [x] Allow editing the model/fields in the admin
* [x] Add filtering on these fields in the admin and show in columns in list_display.
* [x] Also add filtering on `LokaleOverheid`.
