### ISSUE TITLE
Controle functie inbouwen voor reviewers

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#350]
In gesprek met @markbacker is en review-functie besproken maar het was onduidelijk hoe dit precies moest werken en of hier behoefte aan is. Deze zou in ieder geval per taal moeten werken was het idee.

Onderstaande taken zijn niet juist maar gekopieerd uit #24 waar de scope te veel werd opgerekt

**Tasks**

The idea is that we compare `LocalizedGeneriekProduct.datum_check` (A) with `LocalizedProduct.datum_check`.  (B) If A > B, we show a notification on the view/edit pages.

* [ ] Show a message if A > B: "De (Nederlandse [en] Engelse) generieke tekst is aangepast sinds uw laatste controle." This message contains the logic A-EN > B-EN and/or A-NL > B-NL.
* [ ] Make sure `LocalizedGeneriekProduct.datum_check`  is set to the current date/time upon save (for all languages)
* [ ] Add `LocalizedGeneriekProduct.datum_check` as read-only field on detail and edit page, generic section. Name the field: "Laatst gewijzigd"
* [ ] Make sure `LocalizedProduct.datum_check`  is set to the current date/time upon publish (for all languages)
* [ ] Add `LocalizedProduct.datum_check` as read-only field on detail and edit page, specific section. Name the field: "Laatst gecontroleerd"
* [ ] Add a new "Controle"-panel on the detail page, above the "Wijzigen"-button (see mockup below)
* [ ] Pressing "Indienen" will set `LocalizedProduct.datum_check` for the selected languages to today. After clicking you should simply return to the same page.

![image](https://user-images.githubusercontent.com/96970/148078704-6084f17b-c93f-42f0-8e66-8cb98cbd2f2f.png)

**Comment by mrtn78** [comment]
Dit omvat ook issue #214 
_"Als een standaardtekst is gewijzigd in de invoervoorziening wil ik als beheerder bij het inloggen in de invoervoorziening een lijst zien van wijzigingen "_

**Comment by mrtn78** [comment]
Dit kan al door een tekst als concept op te slaan en het concept te laten controleren en publiceren door een collega. Dit is al beschreven in de SDG handleiding en de bestaande redactie werkwijzen bij gemeenten.

in de huidige opzet zijn alle wijzigingen in opgeslagen in de geschiedenis en kunnen publicaties altijd weer worden aangepast.
