### ISSUE TITLE
Oplevering checklist

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#353]
* [x] Documentatie is gereed
* [x] EUPL-licentie staat correct
* [x] CI/CD gaat correct naar acceptatie/productie
* [x] Testplan is doorlopen op acceptatie
* [ ] Projectboard is geschoond
* [x] VNG heeft een clone (#46)
* [ ] Product heeft een release tag gekregen

**Pre-production checklist**

* [x] CI shows no errors for the deployed version
* [x] CD/Ansible has been set up
* [x] Python requirements are up to date
* [x] NPM requirements are up to date
* [x] Deploy checklist shows no warnings/errors (manage.py deploy --check)
* [x] Logging is properly configured
* [x] Caching is properly configured
* [x] Sentry is properly configured
* [x] APM is properly configured
* [x] E-mail werkt naar behoren (blocked by: #227)
* [x] SSL certificates are properly set up

**Comment by joeribekker** [comment]
Aangezien we nog een sprint doen ga ik deze sluiten. Wat gedaan kan worden is gebeurd.
