### ISSUE TITLE
Connect the SDG API to the API testplatform

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#354]
**Tasks**

* [x] Generate postman tests
* [x] Upload postman tests to API testplatform (https://api-test.nl/) - Ask @alextreme for details
* [x] Make sure the tests are executed against our test server

**Comment by alextreme** [comment]
@dariomory take a look at https://api-test.nl/server/2/testscenario/10/ (calls & the postman collection you can download there) as an example
