### ISSUE TITLE
[NF-02] Beveiliging API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#38]
De Producten API ontsluit de productbeschrijvingen naar de nationale portalen en mogelijk ook naar gemeenten en andere geïnteresseerden. De productbeschrijvingen zijn publieke data. 
De Producten API is publiek toegankelijk om te lezen
Afnemers moeten de zekerheid hebben dat zij de door gemeenten beheerde teksten ophalen
De Producten API authentiseert zichzelf met een (PKI) certificaat, opdat de Nationale portalen de zekerheid hebben productteksten van gemeenten te publiceren.

**Tasks**

* [x] De Producten API ontsluit de productbeschrijvingen naar de nationale portalen en mogelijk ook naar gemeenten en andere geïnteresseerden. De productbeschrijvingen zijn publieke data. 
* [x] De Producten API is publiek toegankelijk om te lezen.
* [x] ~De Producten API authentiseert zichzelf met een (PKI) certificaat, opdat de Nationale portalen de zekerheid hebben productteksten van gemeenten te publiceren.~ Niet meer nodig per comment van Martin.

**Comment by mrtn78** [comment]
op basis van het Logius nieuwsbericht [over de uitfasering van publieke PKIO certificaten](https://www.logius.nl/actueel/uitfasering-uitgifte-publiek-vertrouwde-webcertificaten-pkioverheid) stel ik voor om op dit moment gebruik te gaan maken van publieke/gratis Let's Encrypt certificaten. Zie ook [de berichtgeving van het NCSC](https://www.ncsc.nl/actueel/nieuws/2021/september/29/ncsc-publiceert-factsheet-pkioverheid-stopt-met-webcertificaten-kies-een-andere-leverancier).
