### ISSUE TITLE
Various admin improvements

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#399]
These are just small things I noticed in the admin:

* [x] Add doelgroep filter on generic product
* [x] UPN filter SDG is now weird due to being an array of codes. Filter should just be empty or not (like the others). This will require a custom admin filter.
* [x] Sorting and filtering doesn't work correct on the [TOTP devices page ](https://pdc-acc.vng.nl/sdg/admin/otp_totp/totpdevice/)

**Comment by FrankLieuwen** [comment]
ter beoordeling voor volgende sprint

**Comment by mrtn78** [comment]
hi @joeribekker is het mogelijk de change van dit issue als bugfix te deployen?

rede is dat de implementatie adviseurs hier dagelijk tegenaan lopen en de reguliere release pas aan het eind van de sprint is. Ik wil de heren niet te lang laten wachten op deze backend verbetering.
