### ISSUE TITLE
[NF-04] Informatiebeveiliging, Logging activiteiten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#40]
Inschrijver borgt dat alle activiteiten, ook die van Eindgebruikers en Beheerders worden vastgelegd in audit-/ logbestanden. Dit zodanig beveiligd dat deze bestanden niet zomaar kunnen worden ingezien, gewijzigd of verwijderd door hiertoe niet bevoegd personeel
Inschrijver borgt dat een logregel minimaal het volgende bevat:

1. Waar mogelijk een tot een natuurlijke persoon herleidbare identificatie.
2. Waar mogelijk de identiteit van het werkstation of de locatie.
3. Het object waar de handeling op werd uitgevoerd.
4. Het resultaat van de handeling.
5. De gebeurtenis.
De datum en het tijdstip van de gebeurtenis.

**Tasks**

* [x] Add [django-timeline-logger](https://github.com/maykinmedia/django-timeline-logger)
* [x] Log changes (location save, product save, product publish, etc.) done in the CMS. Example can be seen here: https://github.com/open-formulieren/open-forms/pull/686/files
* [x] The logs above should be visible in the admin interface
* [x] Admin actions are logged by default
