### ISSUE TITLE
Als redacteur wil ik begeleid worden met duidelijke aanwijzingen op de startpagina

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#410]
* [ ] Tekstregel toevoegen wat je doet op deze pagina: "Kies je organisatie"
* [ ] VNG oplichten omdat hier de referentieteksten in zitten, wellicht anders tonen want het beheer van standaard teksten.
* [ ] Buttons wellicht laten lezen: Ga naar catalogi van X

**Comment by mrtn78** [comment]
Kies je organisatie.

**Comment by FrankLieuwen** [comment]
kijken wat hiervan nog actueel is na bevindingen kopgroep

**Comment by mrtn78** [comment]
Deze punten zijn niet meer relevant na de laatste releases
