### ISSUE TITLE
Als redacteur wil ik een duidelijke scheiding tussen organisatie instellingen en de invoer in catalogi

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#411]
**Tasks**

* [x] Move locaties/gebruikers to menu, add separator
* [x] Remove tabs entirely.
* [x] Rename Locaties to Organisatie instellingen
* [x] Rename Gebruikers to Gebruikersbeheer

**Original things**

* [ ] Eventueel menu opdelen: Persoonlijk en Organisatie acties
* [ ] Tabjes locaties/gebruikers naar menu verplaatsen voor meer scherm ruimte

**Comment by svenvandescheur** [comment]
https://github.com/maykinmedia/sdg-invoervoorziening/pull/466
