### ISSUE TITLE
Als redacteur wil ik een duidelijk overzicht van alle producten waarin ik een filter kan toepassen

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#412]
**Tasks**

* [x] Refactor naar lijst/kolommen: naam, doelgroep(en), status, laatst gewijzigd/gewijzigd door (vervangt bovenstaande 2 punten)

Out of scope:

* [x] Filters moeten andere items "grijs" maken (muten)
* [x] Lege categorieen weglaten
* [ ] Lijst volledige schermbreedte geven?

Inschatting: 1 week werk

**Comment by svenvandescheur** [comment]
> Filters moeten andere items "grijs" maken (muten)

Niet relevante items worden niet getoond, er is tevens een "real time" tekst filter op de gevonden resultaten welke wel werkt met een "mute".

**Comment by svenvandescheur** [comment]
> Lijst volledige schermbreedte geven?
Laat ik voor nu even in het midden, moeten we in dat geval ook de rest van de containers aanpassen?
