### ISSUE TITLE
Als redacteur wil ik per specifieke tekst registreren wat de bevoegde organisatie is (IM1.5)

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#437]
**Tasks**

* [x] Allow a "Beheerder" to create multiple "Bevoegde Organisaties" in their `LokaleOverheid`. Only a name is needed.
* [x] Make a data migration to set the "organisatie" by default as the first "bevoegde organisatie" for `LokaleOverheid`.
* [x] Add FK "Bevoegde Organisatie" on `Product` model, that can choose from the bevoegde organisaties that are configured on municipality level.
* [x] In the API: Add Product.bevoegdeOrganisatie = {"url", "owmsIdentifier", "owmsPrefLabel", "naam"}
* [x] In the API: Rename Product.organsiatie to Product.verantwoordelijkeOrgansiatie
* [x] In the API and model: Remove Organisatie.verantwoordelijkeOrganisatie
* [x] Can we link a bevoegde organisatie naam to a preflabel? If the preflabel is not found you should be able to fill in your own name. See screenshot below
* [x] Should we split up organisation edits from location edits? Yes, so make 3 pages: 1) Edit organisation contact details; 2) Edit locations; 3) Edit bevoegde organisaties

**Psuedocode wtih Dario**

```
Organisation(model):
   bevoegde_organisatie = M2M(OrgLokaleOverheid)


OrgLokaleOverheid(model):
    custom_naam=CharField()
    lokale_overheid=FK(LokaleOverheid, blank=True, null=True)

    def name():
        if lokale_overheid:
            return lokale_overheid.naam
        else:
            return self.custom_name

LokaleOverheid(model):
   pass
  
# And in Interface

Org Amsterdam
    bevoegde organisaties = [
        Amsterdam
        GarbageDepartment
        PublicTransport
        Parking
    ]


Product Parkingpermit
    bevoegde organisatie = Parking
```

![image](https://user-images.githubusercontent.com/96970/159679168-2b996555-b41a-4736-b9f8-1f2eec1837bf.png)

**Original ticket from Mark**

Voor een specifieke tekst kunnen er twee organisatierollen zijn. Uit het IM1.5 :
- Verantwoordelijke organisatie
   -	De organisatie die verantwoordelijk is voor de procedure. Dit is altijd de decentrale overheid zelf.
- Bevoegde organisatie
   - De organisatie die verantwoordelijk/bevoegd is voor de uitvoering van de procedure. 
   - In geval van een decentrale overheid zou dit een samenwerkingsverband kunnen zijn. Een voorbeeld is de omgevingsvergunning. Gemeenten hebben de uitvoering van het verlenen van omgevingsvergunning vaak belegd bij een regionale omgevingsdienst

Dit heeft flink impact
- tab locaties veranderen in organisatie?
  - registreren gemeente (dit is altijd de verantwoordelijke organisatie en is default ook de bevoegde organisatie)
     - met contactgegevens en locaties zoals nu ook wordt vastgelegd
  - registreren van 0, 1 of meerdere samenwerkingsverbanden (een bevoegde organisatie voor één of meerdere producten)
     -  met contactgegevens en locaties zoals nu van de gemeente wordt vastgelegd
- per specifieke tekst bij de algemene gegevens
  - met radio button selecteren van de bevoegde organisatie voor het huidige product
     - er wordt één bevoegde organisatie geselecteerd
     - default is de gemeente zelf de bevoegde organisatie
     - te wijzigen in één van de geregistreerde bevoegde organisaties
  - vervolgens aanvinken van de locatie(s) van de geselecteerde bevoegde organisatie

**Comment by markbacker** [comment]
@FrankLieuwen klopt bovenstaande verhaal voor jou? 
Zo ja, kun je voor de gemeente Harderwijk een paar producten noemen waarvoor een samenwerkingsverband bevoegd is?

**Comment by FrankLieuwen** [comment]
@markbacker intern nagegaan en conclusie is dat een aantal zaken inderdaad door een Gemeenschappelijke Regeling kan worden uitgevoerd. In Harderwijk is dit bijvoorbeeld het geval voor belastingen waar het gaat mo ca 10 producten van de shortlist.
Voor nu als Medium prioriteit aangemerkt omdat het m.i. niet noodzakelijk is dit ingevoerd te hebben voordat gemeenten aan de gang kunnen (kan aanpassing achteraf zijn).

Eens?

**Comment by markbacker** [comment]
Eens dat we dit moeten gaan bouwen. Dat het bij Harderwijk al gaat om 10 producten is wel significant.

Medium is goed, mits dat betekent dat we het realiseren vóórdat de grote groep gemeenten producten gaat invoeren. We moeten voorkomen dat veel gemeenten alle producten 2 keer door moeten. Voor de koplopers is het denk ik wel acceptabel dat zij dit achteraf nog aanvullen.

Misschien Extra Medium?

**Comment by FrankLieuwen** [comment]
dank, ik zet hem hoog in de backlog op medium (dus niet in sprint 7)
