### ISSUE TITLE
[NF-08] Installeerbaarheid

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#44]
Componenten zijn out-of-the-box geschikt voor installatie binnen een gestandaardiseerde (cloud-)infrastructuur platform (bijvoorbeeld Haven9).

De componenten zijn geautomatiseerd te testen en deployen middels een CI/CD pipeline
Het doorlopen van de pipeline duurt max 1 uur
De voorziening dient als container op (bijvoorbeeld een kubernetes) infrastructuur te kunnen worden gedeployed

**Tasks**

* [x] Docker container bouwen via Github Actions
* [x] Docker container publiceren op Dockerhub
* [x] Unit tests uitvoeren via CI pipeline

In overleg met PO: het daadwerkelijk uitrollen naar een (Haven)omgeving is verplaatst naar een andere (niet must-have) user story.
