### ISSUE TITLE
Als beheerder wil ik near-realtime de generieke teksten van de portalen ophalen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#446]
Besproken met team: Aandachtspunten / realtime opvragen vs bevragen van de eigen dataopslag.

vooralsnog 1x per uur de data ophalen en bij fouten of onbeschikbaarheid de data laten staan. timestamp laatst bijgewerkt bijhouden

**Tasks**

* [x] @markbacker verifieer definitie API specificatie en wat wordt het endpoint, autorisatie methode, etc.
* [x] Add configuration to retrieve data from multiple generic text suppliers (so **not** a solo model)
* [x] Configuration should have an option to choose a "doelgroep" which enforces that this supplier can ONLY set texts for products with that doelgroep.
* [x] Create client to connect with the API, see: https://sdgapi.ondernemersplein.kvk.nl/docs/index.html (see mapping below)
* [x] Retrieve data from all configured APIs to fill generic products

(a second supplier will be added later that uses the same API spec)

**Mapping API-> localized model**

* titel -> product titel
* tekst -> generieke tekst (markdown!)
* links -> verwijzing links
  * label -> label
  * url -> url
  * categorie -> Add new field
* organisaties -> IGNORE
* laatstGewijzigd -> IGNORE
* laatstGecheckt -> datum check
* url -> landelijke link
* upnLabel -> Match Generic product on this field together with the Generic product doelgroep and configured supploer doelgroep.
* taal -> taal
* self -> IGNORE
* id -> IGNORE

**Comment by markbacker** [comment]
Antwoord van Elie

> Bijgaand de meest recente versie van de API specificatie. Op zich is die sinds de vorige versie niet veel veranderd.
>De API zal inderdaad zonder authenticatie gebruikt kunnen worden. De url daarvan weten we ook al en die zal https://sdgapi.ondernemersplein.kvk.nl/ zijn.
>Aangezien wij de generieke teksten inlezen, zullen deze straks direct opvraagbaar zijn via de API en hoeven we dus niet te werken met test data.

> Helaas heb ik wel slecht gekregen over de livegang van de API. Die zal niet deze week live komen te staan omdat er nog wat onverwachte infra zaken geregeld moeten worden. Technisch is de API al af 
> Begin volgende week weet ik wat meer over de planning maar de verwachting is dat het niet veel langer zal duren. Ik houd jullie op de hoogte

[DOP SDG API specs.zip](https://github.com/maykinmedia/sdg-invoervoorziening/files/8151479/DOP.SDG.API.specs.zip)

**Comment by joeribekker** [comment]
Ter info: ik zie deze niet op het sprint board staan

**Comment by joeribekker** [comment]
Je kan en toevoegen uiteraard maar dat creëert niet meer tijd

**Comment by markbacker** [comment]
Laatste bericht van Elie is dat het live zetten van de generieke teksten API vertraagd is.
Elie: Ik verwacht wel dat het uiterlijk volgende week live staat (hopelijk al eerder).

Ik dacht dat deze wel al op het sprint board stond. Laten we DOP afwachten en dan besluiten of dit ten koste van een andere story deze sprint nog mee kan.
