### ISSUE TITLE
[NF-10] Modulariteit

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#46]
Proceslogica en bedrijfsregels zijn los van elkaar en los van de interactie naar gebruikers instelbaar.

Herbruikbaarheid
De broncode van componenten is beschikbaar als open source software met een EUPL-licentie.
De broncode is goed gedocumenteerd
De broncode wordt beheerd in een git-repository van VNG Realisatie

Testbaarheid
De Producten API wordt getest met de API Testvoorziening van de VNG (ATV)

**Tasks**

* [x] De broncode van componenten is beschikbaar als open source software met een EUPL-licentie.
* [x] De broncode is goed gedocumenteerd
* [x] De broncode wordt beheerd in een git-repository van VNG Realisatie (getackled in #353)
* [x] De Producten API wordt getest met de API Testvoorziening van de VNG (zie #354)
