### ISSUE TITLE
Change detail page accoriding to design

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#467]
![image](https://user-images.githubusercontent.com/96970/158147727-138874fe-532c-4a88-b32b-3487e11e8d93.png)

**Tasks**

* [x] Add NL / EN switcher (make sure the active lang is highlighted)
* [x] Add behaviour for "red icon": Show icon next to language if you change lang A and not B. Remove the icon if both texts are changed.
* [x] Add tooltip for "red icon"
