### ISSUE TITLE
[NF-11] Integreerbaarheid

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#47]
De voorziening dient aan te sluiten en gebruik te kunnen maken van de landelijke integratiefaciliteit zoals benoemd in Common Ground
De voorziening dient gebruik te maken van (Linked) Open Data om reeds publiek beschikbare bronnen te kunnen raadplegen en de data te kunnen representeren in de voorziening
Hiermee dienen de koppelingen zoals beschreven in par 5.6 te worden gerealiseerd

**Tasks**

- [x] Create management command to import **SDG** informatiegebieden into the proper models (`Thema, Informatiegebied` yes, we need them). See: https://standaarden.overheid.nl/owms/oquery/SDG-Informatiegebieden.csv -- Can you amend the models to register all columns?
- [x] Create management command to import **UPNs** (Uniforme productnamen) into the proper models (`UniformeProductnaam`). See: https://standaarden.overheid.nl/owms/oquery/UPL-actueel.csv -- Can you amend the models to register all columns?
- [x] Create management command to import **Gemeenten** into the proper models (`Overheidsorganisatie` yep, separate model and we need an extraAttribute "endDate" + querymanager to filter on active gemeenten =< today). See: https://standaarden.overheid.nl/owms/terms/Gemeente.xml

Where it says "Create management command" this should read as "make functions to import the data" and call these functions from a management command. Later on, we might need to do this periodically.
