### ISSUE TITLE
Als redacteur wil ik in een tekstblok alleen subheadings gebruiken

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#472]
**Tasks**

* [x] Limit headings in all markdown editors to H3 and h4

**Original**

De editor van de tekstblokken biedt de redacteur niet alle heading levels aan. De editor beperkt dit tot de levels H2 en H3 of H3 en H4. 
- [ ] In het tekstblok `specifieke tekst` kan gebruik worden gemaakt van H2 en H3
- [ ] In de overige tekstblokken de levels H3 en H4

Hiermee wordt de mogelijke opbouw van een productbeschrijving ingeperkt tot:
- generieke gegevens (zoals aangeleverd door DOP en DPC)
  - `titel`, wordt bij renderen een H1
  - `generieke tekst` met subkoppen H2 en H3
- specifieke gegevens
  - `gemeente titel`, heading level voor renderen nog te bepalen. Wordt een H2 of vetgedrukt in een tekstje?
  - `specifieke tekst` met H2 en H3
  - tekstblokken, zoals `Aanvragen`
    - label, wordt gerenderd als H2
    - tekstblok met subkoppen H3 en H4

**Comment by FrankLieuwen** [comment]
@joeribekker is dit een kwestie van aanzetten in de markdown editor of komt er meer bij kijken?

**Comment by joeribekker** [comment]
Hmm, ik weet niet of we het eenvoudig per blok kunnen laten varieren.

@dariomory What's the effort on limiting the available headings in the markdown editor? And can we make a difference per field?

**Comment by joeribekker** [comment]
Even nagevraagd: Veel eenvoudiger om h2-h4 te limiteren over alles, dan een uitzondering te maken voor een specifiek veld.

**Comment by FrankLieuwen** [comment]
@markbacker is dit werkbaar voor de redacteuren?

**Comment by markbacker** [comment]
Met zoveel redacteuren is het eigenlijk wel gegarandeerd dat hier fouten mee gemaakt gaan worden. Een helptekst zal dit deels voorkomen, maar niet helemaal. 

Veiliger is om alles te limiteren op H3 en H4. De headings zijn dan overal in goede range, behalve in de specifieke tekst. We moeten dan accepteren dat de headings in de specifieke tekst een maatje kleiner zijn dan in de generieke tekst.

Hoe dit uitpakt voor de leesbaarheid, zien we als de portalen live zijn. Dat wordt november ... 

Ik heb een sterke voorkeur om dit toch in de editor op te lossen. Als dit voor deze sprint teveel tijd kost, dan alles limiteren op H3 en H4
