### ISSUE TITLE
[NF-12] Voorkomen gebruikersfouten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#48]
De invoervoorziening valideert de productbeschrijvingen en metadata van de productbeschrijvingen
Bij fouten worden aanwijzingen gegeven hoe de fout hersteld kan worden

**Tasks**

This is about showing form validation errors in the CMS. Make sure an error is shown in the CMS when...

* [x] Filling in incorrect opening hours format
* [x] Filling in incorrect postal code format
* [x] non URLs in URL fields at product edit page
* [x] Setting the publish date in the past
* [x] Whatever else you can think of
