### ISSUE TITLE
Integreer modellen in de beheerinterface

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#5]
**Tasks**

- [x] Register all models as appropriate admin-model
- [x] Use proper admin list fields that make sense
- [x] Add some sorting and filtering options that make sense.
