### ISSUE TITLE
Verwijderen van producten in de invoervoorziening

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#511]
Wanneer in de UPL een product wordt verwijdert (of wanneer de UPN wordt gewijzigd) verdwijnt het product nu niet automatisch uit de invoervoorziening. De voorgestelde werkwijze is ook dat dit productie niet wordt verwijdert maar dat er een status aan wordt toegevoegd waarop de beheerder actie moet ondernemen. Het verwijderen van een Product kan namelijk inhouden dat dit ook impact heeft op de 344 specifieke teksten die voor dit product zijn geschreven.

Voorgestelde statussen zijn:
- Nieuw (Beheerder moet bevestigen dat dit product Gereed is voor gebruik)
- Gereed voor beheer (De Nationale Portalen kunnen generieke teksten aanleveren en de redactie kan de standaard teksten opvoeren)  : Dit is de huidige status van alle producten
- Gereed voor publicatie (De gemeentelijke redactieleden kunnen hun specifieke teksten invoeren en publiceren) : uit een controle moet blijken dat het product een generieke tekst heeft en een standaard tekst heeft. zo niet dat krijgt het product de status:
- ~incompleet (er ontbreken nog generieke teksten of standaard teksten)~
- Vervallen in de UPL (Het product is vervallen in de UPL en Beheer dient actie te ondernemen)
- EOL (End of Life: er is een datum opgegeven waarop het product uit de invoervoorziening wordt verwijdert)
- Verwijdert (het product is verwijdert uit de gebruikersinterface en alleen nog in de beheerinterface terug te zien als historie)

Buiten scope
- archivering product; archivering via webarchiving portalen (nog wel verifieren of dit voor beide portalen geldt)

**Tasks**

* [x] Voeg `is_verwijderd` toe aan `UniformeProductnaam` en die wordt `True` als hij niet gezien wordt tijdens de `load_upn`. Voeg dit veld ook toe in de admin
* [x] Voeg `einddatum` toe aan `GeneriekProduct`. Deze moet in te vullen zijn de admin, en laat zien in de lijst weergave.
* [x] Voeg `def get_status` functie toe aan `GeneriekProduct` die een waarde geeft op basis van onderstaande tabel (uit een DjangoChoices)
* [x] Voeg de belangrijke attributen (is verwijderd, heeft generieke tekst, publicatie_datum, einddatum) hieronder toe aan de admin list views van hun respectievelijke model.
* [x] Voeg get_status toe aan GeneriekProduct list admin view.

Belangrijke attributen:

* `UniformeProductnaam.is_verwijderd` (A)
* `LocalizedGeneriekProduct.generieke_tekst` (B)
* `Product.publicatie_datum` (bij Catalogus.is_referentie=True) (C)
* `GeneriekProduct.einddatum` (D)

Status bepaling:

| Status | A | B | C | D | 
| --- | --- | --- | --- | --- |
| Nieuw | False | is leeg | null  | null |
| Gereed voor beheer | False | is niet leeg | null  | null |
| Gereed voor publicatie | False | is niet leeg | True | null |
| Vervallen in de UPL | True | - | - | null |
| EOL | - | - | - | \< today |
| Verwijdert | - | - | - | \>= today |

**Comment by FrankLieuwen** [comment]
Evt opnemen als vervolg in volgende fase

**Comment by joeribekker** [comment]
Graag toevoegen:

* Voeg `def is_sdg_product` toe aan `GeneriekProduct` die retourneert simpelweg `return bool(self.upn.sdg)` en voeg de kolom toe aan de admin.
