### ISSUE TITLE
Leestoegang tot specifieke teksten

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#576]
### Thema / Theme

CMS

### Omschrijving / Description

Een account kan rechten krijgen waarmee de specifieke teksten van alle gemeenten gelezen kunnen worden.

**Tasks**

* [x] Add new CMS role to users: Raadpleger
* [x] As beheerder you can add a user with this role.
* [x] Users with the role "raadpleger" don't have permission to save products (and hide buttons)
* [x] Users with the role "raadpleger" don't have permission to save organizations
* [x] Users with the role "raadpleger" don't have permission to save/add/delete/edit locations
* [x] Users with the role "raadpleger" don't have permission to edit/invite/etc users

### Added value / Toegevoegde waarde

De GGR redacteuren en implementatieadviseurs moeten met gemeenten kunnen meelezen voor feedback en ondersteuning
De portalen vragen om toegang om te kunnen meelezen

Nu kan dit alleen door een account voor een gemeente redacteur rechten te geven. Dit is ongewenst:
- een redacteur heeft schrijfrechten
- de gemeente beheert wie toegang heeft

### Aanvullende opmerkingen / Additional context

Oplossingsrichting
- toevoegen van de rol raadpleger
- een raadpleger krijgt in zijn dropdown de optie 'Teksten alle gemeenten' 
  - opent pagina met filtertabel met kolommen `product` , `informatiegebied`, `gemeente`
  - het kiezen van een product opent de preview van de producttekst van de gekozen gemeente

**Comment by mrtn78** [comment]
Zie issue #816
