### ISSUE TITLE
Duidelijkere NL|EN switch voor alle tekstblokken

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#617]
### Thema / Theme

CMS

### Omschrijving / Description

Efficienter en duidelijkere UI 

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/1629141/188653711-1c8eb546-eab3-4377-894a-be8cb82da637.png">

**(MINUS NOTIFICATIES & GESCHIEDENIS - Dat komt in ander ticket)**
**(MINUS WITTE BLOKJE RECHTSBOVEN - Dat komt in ander ticket)**

**Tasks**

* [x] Add bar that floats with the content when scrolling down
* [x] Move global NL/EN switcher to bar
* [x] Move preview to bar
* [x] Move "Alles bewerken" to bar

**Comment by mrtn78** [comment]
Dit kan technisch al maar de optie / switch zit verborgen bij de algemene gegevens. functioneel kan het dus beter en duidelijker.

**Comment by mrtn78** [comment]
graag een duidelijk plaats in het scherm maken voor dit soort generieke opties in de UI.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1629141/187452237-6b51310d-2c6a-4f49-b674-05839acb37a9.png">

mogelijk een zwevende knoppenbalk bovenin het scherm in plaats van allemaal losse links en features tussen de tekst door

**Comment by mrtn78** [comment]
Hierbij een impressie van de oplossingsrichting:
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/1629141/188653711-1c8eb546-eab3-4377-894a-be8cb82da637.png">
