### ISSUE TITLE
Rapportage en analyse functionaliteit

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#663]
### Thema / Theme

Admin

### Omschrijving / Description

Als beheerder wil ik graag toegang tot de sdg data omwile van analyse en rapportage, bijvoorbeeld door:
- de database beschikbaar te stellen voor externe analyse tools (Waarstaatjegemeente e.d.)
- een module om overzichten en tabellen te tonen in de admin interface incl. CSV export maar liever toegang tot de database om vervolgens:

- metabase in te zetten voor analyse van de data
- optioneel ook matomo voor user analytics inzetten, tenzij dit al deels standaard in Django zit

**Uitwerkings voorkeuren:**
- bij voorkeur een kopie van de data inzien die geen accountgegevens meer bevat zodat we deze ook niet kunnen lekken.
- bij voorkeur een standaard container met metabase of iets vergelijkbaar toevoegen aan onze deployment waarmee we analyses en rapportages kunnen doen.

### Added value / Toegevoegde waarde

inzicht in de groei van het gebruik:
- aantallen actieve gemeenten
- aantallen producten

optioneel:
- aantal producten wat niet wordt gevoerd (gemeente heeft product xyz niet)
- aantal producten wat valt onder een ander product
- aantal product omschrijvingen wat gelijk is aan de standaardtekst
- % waarin de specifieke teksten afwijken van de standaardteksten
- % van gemeenten wat klaar is

### Aanvullende opmerkingen / Additional context van Mark Backer

User story
Als SDG project wil ik weten in hoeverre gemeenten voldoen aan de SDG verordening, opdat ik kan bijsturen en verantwoorden

Mogelijke oplossingen:

landkaart bij WaarStaatJeGemeente met status per gemeente (nog niks, account, eerste set producten klaar, NL klaar, NL en EN klaar)
openzetten database voor Management Informatie tool
wensen voor overzichten van implementatieadviseurs ...
maatwerk rapportages in/naast de invoervoorziening

Dit moet nog verder worden uitgewerkt.

**Tasks**

In overleg is bovenstaande samengevat in deze taken:

* [ ] Create Ansible-script for Metabase: https://www.metabase.com/start/oss/
* [ ] Configure domain to host it
* [ ] Install on VNG cluster (maybe new server?)
* [ ] Configure Metabase to connect with SDG production-readonly
* [ ] Create Metabase superuser for Mark
* [ ] Export Mark's settings to import them into the deployed instance

**Comment by mrtn78** [comment]
een mooi voorbeeld van de landelijke voorzieningen en de adoptie daarvan door gemeenten staat ook op : https://www.waarstaatjegemeente.nl/dashboard/dashboard/landelijke-voorzieningen

**Comment by joeribekker** [comment]
Dit ticket is klaar of moet verder gespecced worden zoals de laatste zin zegt.

**Comment by mrtn78** [comment]
> Configure domain to host it

preferably the existing domain and only a new path eg.  
- pdc.vng.nl/metabase
