### ISSUE TITLE
Import different tables depending on organization type

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#668]
One of the core features is to import various "tables" from the government. This management command currently is tailored for gemeenten, and should be generalized. The command is:  `sdg.core.tasks.import_logius_data` and is called via a periodic Celery task.

**Tasks**

* [ ] Add a Django settings setting `SDG_ORGANIZATION_TYPE` that can be either `municipalities` or `provinces`
* [ ] Add `PublicData.PROVINCE`:  `owms/terms/Provincie.xml`
* [ ] Depending on the above setting, the URLs that the command uses should be different (ie. load either gemeenten or provinces)
