### ISSUE TITLE
Statistieken

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#691]
**Tasks**

* [x] Add field `Token.last_seen` to keep track of the last time the API-token connected. Show this in the admin token list view.
* [x] In the Product admin list view: Remove column generiek product
* [x] In the Product admin list view: Add columns `aanwezig`, `latest_version` and `latest_publication_date`. These last 2 can be deducted from the version set (and make use of an annotation).
