### ISSUE TITLE
Inzicht in producten met kosten / leges

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#751]
### Thema / Theme

CMS

### Omschrijving / Description

Om gebruiker te helpen de kosten en leges actueel te houden willen we ze graag een overzicht bieden van alle producten waarin kosten en leges worden genoemd.

Het lijkt mij het handigste als we dit realiseren door een nieuwe zoekpagina aan te maken waarmee gebruikers kunnen zoeken op steekwoorden die verband houden met kosten. Denk hierbij aan het woord gratis, euro of het euro teken € . 

het resultaat van de zoekpagina mag een lijst zijn van producten waarbij wellicht het stuk tekst met het steekwoord erin wordt getoond en gehighlight met een kleur.

de gebruikers kunnen vanuit het resultaat doorklikken naar de pagina om de producten te bewerken.

**Tasks**

The above description is no longer accurate. The tasks represents what needs to be done.

* [x] Add new model field `Product.has_costs` (this will not be part of the API)
* [x] Show checkbox below "Betaalmethoden" field in the CMS product edit page
* [x] Add the checkbox (true/false) to the CMS product list view, and filterable
* [x] Make a (one time) data migration that sets the checkbox to true if the "betaalmethoden" field in Dutch contains "€" or "EUR" or "gratis"

### Added value / Toegevoegde waarde

Dit geeft gebruikers meer mogelijkheden om gericht content te onderhouden en actualiseren.

**Comment by mrtn78** [comment]
- [ ] opnemen van een waarde waarin wordt vastgelegd dat een product kosten bevat. (kosten vinkje)
- [ ] in de productenlijst moet dit worden getoond
- [ ] de huidige dataset doorlopen en eenmalig alle producten waarin nu kosten zijn opgenomen het kosten vinkje krijgen
