### ISSUE TITLE
Bevoegde organisatie kan niet aan meerdere organisaties worden toegekend

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#755]
### Product versie / Product version

1.3.0

### Omschrijf het probleem / Describe the bug

Als je nu een bevoegde organisatie wilt toevoegen aan organisatie A en daarna aan organisatie B, dan gaat dat fout (zonder zichtbare foutmelding overigens). Dit komt doordat het "naam" veld `unique=True` heeft. Dit moet een `unique_together` worden met `lokale_overheid`.

**Tasks**

* [x] Change unique on naam to unique_together with lokale_overheid
* [x] Make sure general errors are shown on the form.
* [x] Make sure the API also uses the lokale_overheid to identify the proper bevoegde organisatie when linking them by `naam`
