### ISSUE TITLE
Als ontwikkelaar wil ik de testomgeving beschikbaar maken voor VNG

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#76]
**Tasks**

* [x] Build Docker image
* [x] Add docker-compose files
* [x] Get test environment for the project
* [x] Deploy the test environment
* [x] Gebruikers aanmaken
* [x] Sentry inrichten
* [x] Configuratie afmaken
