### ISSUE TITLE
Meertalige lokatiegegevens

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#794]
### Thema / Theme

CMS

### Omschrijving / Description

In de feedbacksessie die we vanmorgen hadden met gemeenteredacteuren kwamen we achter een issue met het veld `openingstijden_opmerking` en het veld `naam locatie`. 

Op dit moment is er maar 1 optie om deze velden toe te voegen, ipv een aparte NL optie en EN optie.

Wat we nu in de ingevoerde data zien terugkomen is dat de meeste redacteuren dan alleen een Nederlandse opmerking toevoegen.

Mijn voorstel zou zijn dat we:

Voor de korte termijn de opmerking weg laten op de Engelse site en de gemeentes te vragen de opmerking alleen in het Nederlands hier te plaatsen (ik zie dat alleen Gemeente Weert dit nu anders doet).
En dan op de lange termijn het informatiemodel+invoervoorziening aanpassen om hier ook de optie te geven voor een opmerking in het Engels.

### Added value / Toegevoegde waarde

De portalen kunnen op de engelse variant een engelstalige `openingstijden_opmerking` en `naam locatie` tonen

**Comment by joeribekker** [comment]
Niet duidelijk genoeg. Wat wil je nu precies voor de korte termijn? En wat betekent dit voor de API?

**Comment by mrtn78** [comment]
De voorkeur gaat naar een structurele oplossing waarbij we alleen de openingstijdenOpmerking meertalig maken en dit consequent doorvoeren in de API als array van talen.

results": [
    {
      "url": "string",
      "naam": "string",
      "straat": "string",
      "nummer": "string",
      "postcode": "string",
      "plaats": "string",
      "land": "string",
      "vertalingen": [
        {
          "taal": "nl",    
          "openingstijdenOpmerking": "string"
        } 
      ],
      "organisatie": {
        "url": "string",
        "owmsIdentifier": "string",
        "owmsPrefLabel": "string",
        "owmsEndDate": "2022-10-31T11:11:50.116Z"
      },

Een minder wenselijke oplossing is dat een tweede element worden toegevoegd:
    "openingstijdenOpmerkingEng": "string",

het result wordt dan
results": [
    {
      "url": "string",
      "naam": "string",
      "straat": "string",
      "nummer": "string",
      "postcode": "string",
      "plaats": "string",
      "land": "string",
      "openingstijdenOpmerking": "string",
      "openingstijdenOpmerkingEng": "string",
      "organisatie": {
        "url": "string",
        "owmsIdentifier": "string",
        "owmsPrefLabel": "string",
        "owmsEndDate": "2022-10-31T11:11:50.116Z"
      },

**Comment by joeribekker** [comment]
Ik ben voorstander van @mrtn78 in oktober genoemde optie 1 (vertalingen attribuut). Naar de toekomst het meest handig voor als er nog een taal of vertaalbaar attribuut bij komt.

Non breaking gaat het niet worden maar v1 en v2 kunnen prima naast elkaar bestaan. Kan iedereen zelf besluiten wanneer ze overstappen.

Wat betreft de interpretatie van "geen locaties = alle locaties" pleit ik voor verduidelijking in de beschrijving, dat dit niet zo is. Een attribuut toevoegen zoals "alleLocaties=true" en/of "geenLocatie=true" is redundant en voelt als een Fisher-Price API :)

**Comment by mrtn78** [comment]
Input uit het Technisch overleg: 
bron: verslag SDG PGI werkgroep techniek 23 januari 2023

> **Onderwerp 2: vinkjes voor specifieke locaties**
> In de invoervoorziening kunnen gemeenten aanvinken bij welke locatie een product kan worden afgenomen.
> Zij kunnen daartoe locaties aanvinken.
> Als er niets is aangevinkt, zou dat kunnen betekenen dat het product bij alle locaties is af te nemen, maar ook dat het bij geen van de locaties kan worden afgenomen.
> De twee portalen interpreteren dit momenteel verschillend: laten ofwel geen locaties zien (DPC) of allemaal (DOP).
> Het is daarom wenselijk, beamen de aanwezigen, dat er een expliciete optie (vinkje in de invoervoorziening) 'geen locatie' wordt toegevoegd. Bijvoorbeeld voor informatieproducten.
> Dit heeft geen gevolgen voor de API of het informatiemodel, maar moet wel in de systemen van de portalen, invoervoorziening en CMS-en van provincies en waterschappen worden aangepast.
> De vraag is dan wel wie de opdracht hiervoor geeft aan Maykin. Dit leggen we voor aan PGI.

**Comment by mrtn78** [comment]
relates to issue #818

**Comment by joeribekker** [comment]
Ik specificeer dit even voor de maintainer:

* [ ] Checkbox toevoegen bij locaties: Alle locaties (vinkt automatisch alle locaties aan)
* [ ] Het CMS houdt expliciet bij dat dit is aangevinkt. Nieuwe locaties die achteraf worden toegevoegd worden dan automatisch ook aangevinkt.
* [ ] Checkbox toevoegen bij locaties: Geen locatie (vinkt automatisch alle locaties uit!)
* [ ] Visueel onderscheid maken met radiobuttons (hoofdniveau), zie hieronder:

### Mockup

**Locaties:**

* [ ] Alle locaties
* [ ] Geen locaties
* [ ] Specifieke locaties:
   * [ ] Locatie 1
   * [ ] Locatie 2

**Comment by markbacker** [comment]
Input van Marjan van de Waterschappen. 

> Welke velden in de invoervoorziening die nu enkeltalig zijn, moeten in twee talen ingevoerd kunnen worden? 
> 
> Wij denken dat dat deze zijn (van de Algemene gegevens):
> - Organisatieinstellingen:
>   - url website
>   - url contactformulier
> - Locaties:
>   - naam van het kantoor (bijv. Stadskantoor, Belastingssamenwerking, etc.)
>   - opmerkingenveld bij openingstijden
> 
> Voor die 4 velden zou wat ons betreft de optie moeten worden geboden om een Engelse vertaling in te voeren. Maar, als die leeg blijft, wordt de Nederlandstalige tekst getoond. Ofwel, het is dan niet verplicht het Engelstalige veld in te voeren (het is ook niet altijd/voor iedereen van toepassing).

Naam van het kantoor (`naam locatie`) staat bovenin dit issue al genoemd, maar is bij de uitwerking vergeten.

**Comment by mrtn78** [comment]
dit issue is een fundamentele wijziging en daarmee niet een specifiek vng issue

**Comment by RobbieZ69** [comment]
Hoi Joeri, wij vroegen ons af of dit idd bij waterschappen is uitgevoerd, hoe staat het hiermee, de huidige status. Alvast bedankt.
