### ISSUE TITLE
As developer, I want to make the information model more suited as database model

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#80]
Refactor the models on new insights

![image](https://user-images.githubusercontent.com/96970/133461003-fe3e10cb-0815-4f49-bb7d-2f69cf47e6a8.png)

**Tasks**

NOTE: Some of these tasks might already be done.

* [x] Merge `ProductSpecifiekInformatie` and `ProductSpecifiekAanvraag` models into a `Product` model (use this name please).
* [x] Add `Catalogus.is_referentie_catalogus` boolean field (meant to be checked if the catalog holds reference products)
* [x] In the admin, `Catalogus.referentie_catalogus` can **only** link to a Catalog that has `is_referentie_catalogus == True`
* [x] Rename `Product.product` to `Product.referentie_product` as FK to self
* [x] In the admin, only allow `Product.referentie_product` to point to products that belong to a reference catalog (ie. a catalog that has `is_referentie_catalogus == True`)
* [x] Only allow `Product.generiek_product` relation to be filled when the `ProductSpecifiekInformatie` belongs to reference catalog. Thus, this is also an optional field.
* [x] Remove `Standaard*` models (they are replaced by the reference catalog) and related mixins.

When these tasks are done, the following rough workflow should be possible in **later user stories for CMS views** (note: this is just a rough idea, code added for developer clarity):

1. Admin imports `UniformeProductnaam` (`UPN`)
2. Admin imports or adds (localized) `GeneriekProduct` GP and links to `UPN`
3. Admin creates reference `Catalogus` (`is_referentie_catalogus = True`) called C
4. Reference editor logs in, sees reference `Catalogus`
5. Reference editor adds new (localized) `Product` P, Q, K to reference `Catalogus` C and selects the appropriate `GeneriekProduct` GP
6. Municipality editor logs in (for the first time) as `LokaleOverheid` X.
7. System creates a new `Catalogus` (C1) for each `Catalogus` (only C atm) that doesn’t have a match yet and has 
   ```python
   # On logging in as user for X, something like this should happen:
   for c in Catalogus.objects.filter(is_referentie_catalogus=True):   # Returns [C]
     Catalogus.objects.create(referentie_catalogus=c, lokale_overheid=X)
   ```
8. Municipality editor sees available catalogs (just C1) including all products from `Catalogus` C (products P, Q and K) intersected with those in `Catalogus` C1 (no products present): **resulting in showing P, Q and K.**
9. Municipality editor wants to edit Product P…
10. The system detects `Product` P has no match in `Catalogus` C1 and creates `Product` P1 in `Catalogus` C1, setting P1.referentie_product = P.
    ```python
    # Let's assume the list of products has a URL for products that do not
    # exist in the LokaleOverheid's catalog, like:
    # /products/create-from-reference/<referentie_product=P>.
    # This view will just create the product with defaults and redirect to the edit page.
    class CreateFromReferenceView(ModelView):
      model = Product

      def get(self, *args, **kwargs):
        c1 = Catalogus.objects.get(lokale_overheid=X, referentie_catalogus=self.referentie_product.catalogus)  
        p1 = Product.objects.create(referentie_product=self.referentie_product, catalogus=c1)  # set some more defaults?
        return HttpRedirect(reverse('product-edit-form', kwargs={"pk": p1.pk}))
    ```
11. Municipality editor sees available catalogs (just C1) including all products from `Catalogus` C (products P, Q and K) intersected with those in `Catalogus` C1 (product P1): **resulting in showing P1, Q and K.**

At this point there is a Catalog C with Product P, Q, K and Catalog C1 with just Product P1

If you want to use the reference texts for Product P1, simply follow: `P1.referentie_product` (which returns P, which is the reference product)
