### ISSUE TITLE
Deel 2 : Leestoegang tot specifieke teksten

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#816]
### Thema / Theme

CMS

### Omschrijving / Description

Een account kan rechten krijgen waarmee de specifieke teksten van alle gemeenten gelezen kunnen worden.

> Dit issue is een afsplitsing/opvolging van issue #576

### Added value / Toegevoegde waarde

De GGR redacteuren en implementatieadviseurs moeten met gemeenten kunnen meelezen voor feedback en ondersteuning
De portalen vragen om toegang om te kunnen meelezen

Nu kan dit alleen door een account voor een gemeente redacteur rechten te geven. Dit is ongewenst:

- een redacteur heeft schrijfrechten
- de gemeente beheert wie toegang heeft
- 

### Aanvullende opmerkingen / Additional context

- [x] toevoegen van de rol raadpleger is gedaan in issue #576
- [ ] een raadpleger krijgt in zijn dropdown de optie 'Teksten alle gemeenten'
- [ ] opent pagina met filtertabel met kolommen product , informatiegebied, gemeente
- [ ] het kiezen van een product opent de preview van de producttekst van de gekozen gemeente
