### ISSUE TITLE
Make mentions of "gemeenten" configurable

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#827]
We now use the type of organization "gemeenten" quite explicit in various areas. We need to make this configurable based on the setting: `SDG_ORGANIZATION_TYPE ` -> https://github.com/maykinmedia/sdg-invoervoorziening/pull/826/files#diff-37a47da3a802978635299a155761b63c7cada3a892ce2b35e3a2931aea21dc98R547

* `municipalities` -> gemeente / gemeenten (plural)
* `provinces` -> provincies / provincies
* `waterauthorities` -> waterschap / waterschappen

**Tasks**

* [ ] Add HWH logo https://cuatro.sim-cdn.nl/hetwaterschapshuis/uploads/styles/logo/media/logo-het-waterschapshuis.png and existing IPO logo to footer (can be static, all 3) and API page.

Make these things dependent on the `SDG_ORGANIZATION_TYPE `:

* [ ] Logo subheader (voor gemeenten)
* [ ] Email account invitation subject and email account body
* [ ] `BevoegdeOrganisatieUpdateView`, `LocatieUpdateView`, `RoleDeleteView`, `RoleUpdateView` success message
* [ ] `default_explanation_mapping` and `default_aanwezig_toelichting_explanation_mapping`
* [ ] `login_dashboard.html`: Intro message "Hier beheert u gemeente specifieke teksten voor gemeentelijke producten." (can remove the "gemeentelijke")
* [ ] `icon.html` texts can be generalized to "Mijn organisatie ..."
