### ISSUE TITLE
Nederlandse en Engelse teksten lopen in de preview door elkaar

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#838]
### Product versie / Product version

1.5.0

### Omschrijf het probleem / Describe the bug

in navolging op issue #758 : De nederlandse preview heeft engelse tekst en de engelse preview heeft nog nederlandse tekst

### Stappen om te reproduceren / Steps to reproduce

go to product
open preview
switch between NL | ENG

### Tasks

* [x] Translate what needs to be translated to get a proper NL and EN page (we can check together @dariomory )
* [x] Add compile messages to Dockerfile
* [x] Translate labels in PO file
