### ISSUE TITLE
Als redacteur wil ik een gepubliceerde tekst voor de portalen kunnen verbergen

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#845]
### Thema / Theme

CMS

### Omschrijving / Description

![image](https://user-images.githubusercontent.com/96970/203828731-ebdd37ec-22e3-43f6-a669-932167a7d54e.png)

Verbergen aanvinken maakt het product onzichtbaar in de API

### Added value / Toegevoegde waarde

Als een gemeente per abuis/te snel op publiceren heeft gedrukt, kan de gemeente de tekst weer verbergen.
Kwaliteit van de gepubliceerde teksten is beter. Keerzijde is dat er minder teksten gepubliceerd zijn

### Tasks

* [x] Add new boolean field `Product.hidden`. Default is False. It indicates whether or not the (published) product is visible in the API. Label: "Zichtbaarheid". Help text: "Verbergen voor Nationale Portalen."
* [x] Make the label and help text manageable from the admin.
* [x] Add the `Product.hidden` field to the CMS
* [x] Products with `hidden=False` should not return any results in the API (detail/list)

**Comment by joeribekker** [comment]
Voorstel:

![image](https://user-images.githubusercontent.com/96970/203825615-822a05fa-8cef-4342-a5d9-027d914e2c76.png)

Door onzichtbaar aan te vinken, wordt het product niet meer beschikbaar via de API en dus "onzichtbaar" voor de portalen.

**Comment by joeribekker** [comment]
Als dit akkoord is, graag nog aanleveren WAAR dit vinkje moet komen en wat de teksten zijn van het label, de tekst achter het vinkje en het info-bolletje.

**Comment by markbacker** [comment]
Redacteuren moeten in de productlijst kunnen zien voor welke producten zij verborgen hebben. Bijvoorbeeld in een extra kolom naast de publicatiedatum. 

Dit overzicht is nodig om te voorkomen dat redacteuren vergeten de verborgen vink weer weg te halen.

Reactie op tekst label en plek volgt nog

**Comment by joeribekker** [comment]
> Reactie op tekst label en plek volgt nog

Te laat, is al gebouwd :)

> Bijvoorbeeld in een extra kolom naast de publicatiedatum.

Je weet dat er niet oneindig kolommen kunnen hebben he? ;-)

**Comment by markbacker** [comment]
Ik voeg net toe of het mogelijk is de tekst van de regel heel lichtgrijs te kleuren? kost geen ruimte

**Comment by joeribekker** [comment]
Ha, ja, zal even kijken wat kan :)

**Comment by markbacker** [comment]
Label en toelichting worden: 
‘Tekst verbergen’ plus ‘De tekst wordt niet getoond op de nationale portalen’. 

Tooltip: Gebruik de functie 'tekst verbergen' als je ontdekt dat een tekst storende fouten bevat, maar nu geen tijd hebt deze te verbeteren

**Comment by mrtn78** [comment]
graag deze feature nog niet uitrollen. binnen het team moet nog goed worden besproken wat dit dan betekent, welke informatie portalen dan tonen hoe we dit meten/sturen enzovoorts.

**Comment by mrtn78** [comment]
Issue kan worden gesloten . dit gaan we niet verder oppakken. de optie is niet meer zichtbaar in de UI en dat houden we zo.
