### ISSUE TITLE
Create a new API to serve the generic texts

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#847]
Since we already load in the generic texts, we can also expose these texts using the same API specification. We function as proxy as sorts, with caching layer.

The schema can be found here: https://sdgapi.ondernemersplein.kvk.nl/swagger/v1/swagger.yaml

```json
{
  "count": 92,
  "next": "https://a-api.nederlandwereldwijd.nl/sdg/gt/v1/producten?page=2",
  "results": [
    {
      "titel": "Applying for a disabled parking space",
      "tekst": "....",
      "links": [
        {
          "label": "Lokale wet- en regelgeving",
          "url": "https://lokaleregelgeving.overheid.nl/",
          "categorie": "wetgeving"
        }
      ],
      "organisaties": [
        {
          "rol": "Verantwoordelijke organisatie",
          "owmsPrefLabel": "Ministerie van Buitenlandse Zaken",
          "owmsUri": "http://standaarden.overheid.nl/owms/terms/Ministerie_van_Buitenlandse_Zaken"
        }
      ],
      "laatstGewijzigd": "2022-10-17T09:34:02",
      "laatstGecheckt": "2022-09-21T09:25:00",
      "url": "https://a-www.p1g.nl/government-services-in-the-netherlands/applying-disabled-parking-space",
      "upnUri": "http://standaarden.overheid.nl/owms/terms/gehandicaptenparkeerplaats",
      "upnLabel": "gehandicaptenparkeerplaats",
      "taal": "en",
      "self": "https://a-api.nederlandwereldwijd.nl/sdg/gt/v1/producten/e4f21335-5bb7-47d6-ab8c-f916d2c37286",
      "id": "e4f21335-5bb7-47d6-ab8c-f916d2c37286"
    },
# ....
```

**Tasks**

* [ ] Add a new API on `/gt/api/v1` resource `producten` to return the list shown above, using our database as input.
* [ ] Add the detail endpoint as well
* [ ] Modify our database model where needed (i think we still lack `links.category` and some meta properties (`self`, `id`?) to store all info
* [ ] Add 1 more attribute in the API, below `title`: `doelgroep` which is the same doelgroep as we currently have in the generic product model. There should also be a query filter in the API on doelgroep (in addition to the regular filters in their API).
* [ ] Use the same field descriptions from the schema
* [ ] Implement the same query parameters to filter the list.

**Dario**

* [ ] Move UUID field to LocalizedGenericProduct model
* [ ] Create/Update migrations to add empty UUID field to LocalizedGenericProduct <-- Localized!!!
* [ ] Add data migration to update generic products with the UUID from the services
* [ ] Add migration to make UUID field unique and not-nullable again
* [ ] Add category-field to links to LocalizedGenericProduct
* [ ] Add laatst-gewijzigd to LocalizedGenericProduct
* [ ] Make sure the management command is updated to fill the above new fields
