### ISSUE TITLE
[US-03] Als Gemeente Redactie wil ik locatiegegevens kunnen wijzigen en toevoegen zodat deze actueel blijven

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#9]
Een gemeente kan meerdere locaties hebben waar diensten worden geleverd

**Acceptatiecriteria** :
* Na het toevoegen is de locatie direct zichtbaar in het overzicht
* Na het toevoegen kan de locatie gebruikt worden om producten aan te koppelen

**Tasks**

* [x] Modify Lokatie model to include `openingstijden` for each day, and ~adres~, `straat, nummer, postcode, plaats, land, website, telefoonnummer, email`
* [x] Add view/form/template to edit Lokatie details.
* [x] Allow a new location to be added.

![image](https://user-images.githubusercontent.com/96970/130621641-ca152673-a201-4077-90bd-277f3c2a5679.png)
