### ISSUE TITLE
Verbeteringen Q4-2024

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#986]
* [ ] Slotjes verwijderen
Punt 1: Alle slotjes worden verwijderd en daarmee zijn alle velden altijd bewerkbaar.

* [ ] Volgorde van locaties kunnen wijzigen
Punt 2: We voegen naast locatie titel toe: (up-icon) Verplaats omhoog | (down-icon) Verplaats omlaag

* [ ] Geschiedenis sorteren op datum
Punt 3 (backend): Volgorde van geschiedenis wordt gesorteerd op datum. We passen de geschiedenis tekst aan zodat het product niet meer zichtbaar is, om ruimte te besparen (het product is immers het product waar je op dat moment bent).

* [ ] Navigatie menu toevoegen met notificaties
Punt 4: We voegen het navigatie menu toe onder de titel. De items uit het navigatie menu, worden uit het "profiel" menu gehaald.
Als er nieuwe notificaties zijn, komt er een uitroepteken naast het menu item "notificaties" te staan. Of er nieuwe notificaties zijn, wordt bepaald door: Nieuw = Notificatie pagina bekeken datum <= Laatst notificatie datum.

* [ ] Duidelijkere fout-indicatie bij editor
Punt 5: We voegen een rode lijn toe, om de editor, om aan te geven waar de fout zit.

* [ ] Nederlands en Engels naast elkaar
Punt 6: Layout van de generieke teksten (2), en de specifieke teksten (3), worden in 2 kolommen geplaatst zodat in de eerste kolom de Nederlandse versie staat, en de tweede kolom, de engelse versie. De kopjes, en taal, worden boven de editors geplaatst, zodat er meer ruimte is voor de kolommen. De knoppen onder de editors, worden zodanig gewijzigd zoals te zien is in het ICATT-advies van 7 juli 2024, punt 6.
De algemene gegevens (1), blijven over de breedte van de pagina zoals dat nu is.

* [ ] Periodieke mail sturen met foutieve links
Punt 7 (backend): Er wordt een (niet-configureerbare e-mail gestuurd naar alle "redacteuren" die zijn opgevoerd in de SDG-invoervoorziening en "ontvangt email" aan hebben staan. Dit gebeurt elke maand, met een overzicht van alle links die meer dan 3 x een foutmelding (bijv. 404) gaven als ze opgevraagd worden.

* [ ] Teksten doordrukken
Punt 8: Nader te bespreken

* [ ] Informatiegebied uit productenlijst en geen inleidende tekst
Punt 9: De kolom "informatiegebied" wordt verwijderd uit de lijstweergave, en de inleidende tekst op deze pagina ook.

Punt 10: Vervalt op aangeven van VNG.

Punt 11: We voegen "Mijn instellingen" toe aan het profiel-menu, die direct naar je eigen instellingen gaat. Een redacteur ziet dus enkel deze optie, en niet meer gebruikersbeheer.
De header-balk wordt kleiner. Het navigatie-pad gaat de gemeente-naam bevatten, en de gemeente-naam verdwijnt uit de header. Het wissel-icoon verdwijnt ook en daar kom je nu op, als je op het huis-icoontje uit het navigatie-pad klikt.

* [ ] Verwijder blauwe balk in edit-scherm
Punt 12: Blauwe balk wordt verwijderd.

Punt 13 Vervalt op aangeven van VNG.

* [ ] Producten aanbieden optioneel standaard op Nee zetten
Punt 14 (backend): We voegen dezelfde optie toe bij VNG-teksten als bij gemeenten: "Biedt u dit product aan?". Als VNG dit op "Nee" zet, wordt dit de standaard waarde als het product beschikbaar wordt voor gemeenten. Standaard staat het bij VNG (en dus de gemeenten) op "Onbekend".
